export const translations = {
  id: {
    dashboard: {
      total_mahasiswa: 'Total Seluruh Mahasiswa',
      semua_learning_corner: 'Semua Learning Corner',
      total_project: 'Total Semua Project',
      total_sertifikat: 'Total Semua Sertifikat',
      perihal_terbaru: 'Perihal Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'Sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Project Dikerjakan',
      total_sertifikat: 'Total Sertifikat Didapat',
      perihal_terbaru: 'Perihal Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
    },
    project: {
      project_saya: 'Project Saya',
      deskripsi: 'Kelola project milikmu, yang kamu pimpin, dan yang kamu ikuti sebagai anggota tim.',
      tambah_project: 'Tambah Project Baru',
      edit_project: 'Edit Project',
      hapus_project: 'Hapus Project',
      pemilik: 'Pemilik',
      leader: 'Leader',
      anggota: 'Anggota',
      no_project: 'Belum ada project yang terkait dengan akunmu.',
      dibuat_oleh: 'Dibuat oleh',
      mulai: 'Mulai',
      selesai: 'Selesai',
      lihat_project: 'Lihat Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      tambah_project: 'Tambah Project Baru',
        edit_project: 'Edit Project',
        edit_project: 'Edit Project',
      desc_create: 'Tambah project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
    },
    project_detail: {
      detail_project: 'Detail Project',
      desc_detail: 'Lihat detail project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      students_involved: 'Siswa Terlibat',
      tambah_pemimpin: 'Pemimpin Tim',
      no_leader: 'Tidak ada leader',
      tambah_rekan: 'Rekan Rekan Kerja',
      no_member: 'Tidak ada rekan',
      time_period: 'Periode Waktu',
      links: 'Link',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Hapus Terpilih',
      add_new_note: '+ Tambah Catatan Baru',
      no_learning_corner: 'Belum ada catatan Learning Corner di project ini.',
      select_to_delete: 'Pilih untuk dihapus',
      edit: 'Edit',
      delete: 'Hapus',
      status_incoming: 'Akan Datang',
      status_present: 'Sedang Berjalan',
      status_past: 'Selesai',
      progress_done: 'Selesai',
    },
    portofolio_user: {
      portfolio: 'Portfolio',
    },
    search: {
      search: 'Cari',
      search_placeholder: 'Cari project, sertifikat, atau learning corner...',
      filter_jurusan: 'Semua Jurusan',
      filter_keahlian: 'Semua Keahlian',
      filter_angkatan: 'Semua Angkatan',
    },
    result_search: {
      hasil_pencarian: 'Hasil Pencarian',
      filter_aktif: 'Filter aktif:',
    },
    sidebar: {
      dashboard: 'Dashboard',
      my_dashboard: 'My Dashboard',
      project_mahasiswa: 'Project Mahasiswa',
      project_mahasiswa_saya: 'Project Saya',
      project_mahasiswa_saya_tambah: 'Tambah Project Baru',
      sertifikat_mahasiswa: 'Sertifikat Mahasiswa',
      sertifikat_mahasiswa_saya: 'Sertifikat Saya',
      sertifikat_mahasiswa_saya_tambah: 'Tambah Sertifikat',
      corner_mahasiswa: 'Corner Mahasiswa',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Bahasa',
      logout: 'Logout',
      login: 'Masuk',
      login_prompt: 'Kamu Mahasiswa? Login Sekarang!',
      register: 'Register',
    },
     footer: {
      footer_rights: '© Portofolio Mahasiswa 2026. Semua hak dilindungi undang-undang.',
    },
    project_user: {
      project_user_title: 'Project ',
      project_user_desc: 'Daftar project yang kamu ikuti sebagai anggota.',
      nama_project: 'Nama Project',
      tanpa_nama_project:      "Tanpa Nama Project",
      tidak_diketahui:         "Tidak diketahui",
      selesai:                 "Selesai",
      sedang_berjalan:         "Sedang Berjalan",
      akan_datang:             "Akan Datang",
      sekarang:                "Sekarang",
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
      diposting: 'Diposting',
      no_thumbnail_text: 'Tidak ada thumbnail tersedia',
      no_thumbnail_description: 'Tambahkan link video dengan benar',
    },
  },
  en: {
    dashboard: {
      total_mahasiswa: 'Total Students',
      semua_learning_corner: 'All Learning Corners',
      total_project: 'Total Projects',
      total_sertifikat: 'Total Certificates',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Projects Done',
      total_sertifikat: 'Total Certificates Earned',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',
      
    },
    portofolio_user: {
      portfolio: 'Portfolio',
    },
    project: {
      project_saya: 'My Projects',
      deskripsi: 'Manage your projects, both those you lead and those you participate in as a team member.',
      tambah_project: 'Add New Project',
      edit_project: 'Edit Project',
      hapus_project: 'Delete Project',
      pemilik: 'Owner',
      leader: 'Leader',
      anggota: 'Members',
      no_project: 'No projects associated with your account.',
      dibuat_oleh: 'Created by',
      mulai: 'Start',
      selesai: 'Finish',
      lihat_project: 'View Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      desc_create: 'Add projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      tambah_pemimpin: 'Add Leader (optional)',
      tambah_rekan: 'Add Members (optional)',
      tambah_rekan_btn: '+ Add Members',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date (optional)',
      link_project_opsional: 'Project Link (optional)',
      link_github_opsional: 'GitHub Link (optional)',
      link_video_opsional: 'Video Link (YouTube, optional)',
      simpan_project: 'Save Project',
    },
    project_detail: {
      detail_project: 'Project Detail',
      desc_detail: 'View details of projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      students_involved: 'Students Involved',
      tambah_pemimpin: 'Team Leader',
      no_leader: 'No leader',
      tambah_rekan: 'Team Members',
      no_member: 'No members',
      time_period: 'Time Period',
      links: 'Links',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Delete Selected',
      add_new_note: '+ Add New Note',
      no_learning_corner: 'No Learning Corner notes in this project.',
      select_to_delete: 'Select to delete',
      edit: 'Edit',
      delete: 'Delete',
      status_incoming: 'Upcoming',
      status_present: 'Ongoing',
      status_past: 'Finished',
      progress_done: 'Done',
    },
    search: {
      search: 'Search',
      search_placeholder: 'Search projects, certificates, or learning corners...',
      filter_jurusan: 'All Majors',
      filter_keahlian: 'All Skills',
      filter_angkatan: 'All Cohorts',
    },
    result_search: {
      hasil_pencarian: 'Search Results',
      filter_aktif: 'Active filter:',
    },
    sidebar: {
      dashboard: 'Dashboard',
      my_dashboard: 'My Dashboard',
      project_mahasiswa: 'Student Projects',
      project_mahasiswa_saya: 'My Projects',
      project_mahasiswa_saya_tambah: 'Add New Project',
      sertifikat_mahasiswa: 'Student Certificates',
      sertifikat_mahasiswa_saya: 'My Certificates',
      sertifikat_mahasiswa_saya_tambah: 'Add New Certificate',
      corner_mahasiswa: 'Student Corner',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Language',
      logout: 'Logout',
      login: 'Login',
      login_prompt: 'Are you a student? Login now!',
      register: 'Register',
    },
    footer: {
      footer_rights: '© 2026 Portofolio Mahasiswa. All rights reserved.',
    },
    project_user: {
      project_user_title: 'Project',
      project_user_desc: 'List of projects you participate in as a member.',
      nama_project: 'Project Name',
      tanpa_nama_project:      "Untitled Project",
      tidak_diketahui:         "Unknown",
      selesai:                 "Finished",
      sedang_berjalan:         "Ongoing",
      akan_datang:             "Upcoming",
      sekarang:                "Now",
      diposting: 'Posted',
      no_thumbnail_text: 'No thumbnail available',
      no_thumbnail_description: 'add a video link correctly',
    },
  }
};

export function getTranslation(page, key) {
  const lang = localStorage.getItem('lang') || 'id';
  return translations[lang]?.[page]?.[key] || key;
}

export function updateTranslations() {
  const lang = localStorage.getItem('lang') || 'id';
  document.querySelectorAll('[data-translate]').forEach(el => {
    const page = el.getAttribute('data-translate-page') || 'dashboard';
    const key = el.getAttribute('data-translate');
    el.textContent = translations[lang]?.[page]?.[key] || key;
  });
}

document.addEventListener('turbo:load', updateTranslations);
document.addEventListener('DOMContentLoaded', updateTranslations);
