export const translations = {
  id: {
    
    msh_lrn_add: {
      ttl_form: 'Tambah Catatan Baru',
      desc_form: 'Tulis apa yang kamu pelajari hari ini atau bagikan ilmu yang ingin kamu simpan.',
      ttl_lrn: 'Judul Catatan',
      add_content: 'Konten Tambahan (opsional)',
      add_item: 'Tambah Item',
      del: 'Hapus',
      add_text: 'Tambahkan Teks',
      add_img: 'Gambar',
      add_link: 'Link/Referensi',
      sv_lrn: 'Simpan Catatan',
    },
    
    msh_project_task: {
      add_task: 'Tambahkan tugas',
      add: "Tambah Tugas",
      rsp_task: 'Penanggung Jawab',
      nm_task: 'Nama Tugas',
      pick_rsp: '-- Pilih Penanggung Jawab --',
    },
    pjt_detail: {
      edit_project: 'Edit Proyek',
      desc_pjt: 'Deskripsi Proyek',
      empty_desc: 'Tidak ada deskripsi untuk proyek ini.',
      tm_pjt: 'Timeline Proyek',
      tm_start: 'Mulai',
      tm_end: 'Selesai',
      tm_none: 'Belum ditentukan',
      own_pjt: 'Pemilik',
      link_pjt: 'Link Terkait',
      empty_link: 'Tidak ada link terkait',
      lead_pjt: 'Pemimpin Proyek',
      tim_pjt: 'Anggota Tim',
      empty_tim: 'Belum ada anggota tim',
      lrn_pjt: 'Learning Corner',
      desc_lrn_pjt: 'Catatan dan dokumentasi proyek',
      empty_lrn: 'Belum ada catatan learning corner',
      desc_empty_lrn: 'Mulai tambahkan catatan pertama untuk proyek ini',
      del_sel: 'Hapus Terpilih',
      sel_del: 'Pilih untuk dihapus',
      del: 'Hapus',
      add_lrn: 'Tambah Catatan'
    },
    popup: {
      dashboard: 'Kelola dashboard anda disini. Pantau aktivitas dan proyek terbaru.',
      portofolio_saya: 'Lihat portofolio Anda yang menampilkan semua proyek, sertifikat, dan learning corner yang telah Anda buat.',
      project_saya: 'Kelola semua proyek Anda di sini. Tambah, edit, atau hapus proyek untuk melengkapi portofolio.',
      sertifikat_saya: 'Kelola sertifikat Anda di sini. Tambah sertifikat baru dari lembaga yang berbeda untuk meningkatkan kredibilitas.',
      learning_corner_saya: 'Kelola learning corner Anda di sini. Bagikan pengetahuan dan pengalaman yang Anda pelajari dengan komunitas.',
      profile_saya: 'Edit profil Anda untuk menampilkan informasi pribadi, bio, dan foto profil yang menarik.',
      semua_portofolio: 'Jelajahi portofolio dari mahasiswa lain. Lihat berbagai proyek, sertifikat, dan pencapaian mereka.',
      semua_project: 'Lihat semua proyek yang telah dipublikasikan oleh komunitas. Inspirasi dan kolaborasi dimulai dari sini.',
      semua_sertifikat: 'Lihat sertifikat dari berbagai mahasiswa. Pelajari dan dapatkan inspirasi dari pencapaian mereka.',
      semua_learning_corner: 'Akses learning corner dari seluruh komunitas. Bagikan dan pelajari pengalaman berharga dari sesama mahasiswa.',
      add_angkatan: 'Tambah Angkatan Baru untuk mengelompokkan mahasiswa berdasarkan tahun masuk mereka. Kelola angkatan untuk memudahkan pengelolaan data mahasiswa.',
      edit_angkatan: 'Edit informasi angkatan yang sudah ada. Perbarui nama, tahun masuk, atau tahun keluar untuk menjaga data angkatan tetap akurat.',
      detail_angkatan: 'Lihat detail angkatan, termasuk daftar mahasiswa yang terdaftar, statistik, dan informasi penting lainnya.',
      add_project: 'Tambah proyek baru untuk mahasiswa. Admin dapat membantu membuat dan mengisi portofolio project mahasiswa dengan informasi lengkap.',
      user_detail_project: 'Lihat detail proyek mahasiswa. Tampilkan informasi lengkap tentang proyek, anggota tim, dan file terkait.',
      user_edit_project: 'Edit proyek mahasiswa yang sudah ada. Admin dapat membantu memperbarui informasi proyek, anggota tim, atau file terkait untuk menjaga portofolio tetap up-to-date.',
      edit_project: 'Edit informasi project yang sudah ada. Perbarui detail proyek, anggota tim, atau file project sesuai kebutuhan.',
      add_sertifikat: 'Tambah sertifikat baru untuk mahasiswa. Pilih mahasiswa dan masukkan informasi sertifikat termasuk nama, lembaga penerbit, dan file sertifikat.',
      user_create_project: 'Buat proyek baru untuk mahasiswa. Admin dapat membantu membuat dan mengisi portofolio project mahasiswa.',
      edit_sertifikat: 'Edit informasi sertifikat yang sudah ada. Perbarui nama sertifikat, lembaga penerbit, tanggal terbit, atau file sertifikat sesuai kebutuhan.',
      user_create_sertifikat: 'Tambah sertifikat baru untuk mahasiswa. Pilih mahasiswa dan masukkan informasi sertifikat termasuk nama, lembaga penerbit, tanggal terbit, dan file sertifikat.',
      user_edit_sertifikat: 'Edit informasi sertifikat yang sudah ada. Perbarui nama sertifikat, lembaga penerbit, tanggal terbit, atau file sertifikat sesuai kebutuhan.',
      dosen_add_project: 'Tambah proyek baru untuk mahasiswa. Dosen dapat membantu membuat dan mengisi portofolio project mahasiswa dengan informasi lengkap.',
      dosen_edit_project: 'Edit informasi project yang sudah ada. Perbarui detail proyek, anggota tim, atau file project sesuai kebutuhan.',
      dosen_add_sertifikat: 'Tambah sertifikat baru untuk mahasiswa. Dosen dapat membantu membuat dan mengisi portofolio sertifikat mahasiswa dengan informasi lengkap.',
      dosen_edit_sertifikat: 'Edit informasi sertifikat yang sudah ada. Perbarui detail sertifikat, lembaga penerbit, tanggal terbit, atau file sertifikat sesuai kebutuhan.',
      dosen_add_user: 'Tambah user baru ke sistem. Pilih role (Admin, Mahasiswa, atau Dosen) dan isi informasi lengkap untuk user baru.',
      dosen_edit_user: 'Edit informasi user yang sudah ada. Perbarui nama, username, email, atau role sesuai kebutuhan.',
      dosen_learning_corner: 'Kelola semua postingan Learning Corner dari mahasiswa. Lihat, edit, atau hapus catatan pembelajaran sesuai kebutuhan.',
      dosen_daftar_mahasiswa: 'Kelola semua mahasiswa yang terdaftar dalam sistem. Lihat detail mahasiswa, approve atau reject pengajuan, dan kelola informasi mahasiswa sesuai kebutuhan.',
      dosen_projects: 'Kelola semua proyek yang terdaftar dalam sistem. Lihat detail proyek, edit, atau hapus proyek sesuai kebutuhan.',
      dosen_certificates: 'Kelola semua sertifikat yang terdaftar dalam sistem. Lihat detail sertifikat, edit, atau hapus sertifikat sesuai kebutuhan.',
      add_user: 'Tambah user baru ke sistem. Pilih role (Admin, Mahasiswa, atau Dosen) dan isi informasi lengkap untuk user baru.',
      edit_user: 'Edit informasi user yang sudah ada. Perbarui nama, username, email, atau role sesuai kebutuhan.',
      manage_users: 'Kelola semua user yang terdaftar dalam sistem. Lihat detail user, perbarui status, edit informasi, atau hapus user sesuai kebutuhan.',
      user_create_learning_corner: 'Buat catatan learning corner baru untuk mahasiswa. Pilih mahasiswa dan isi informasi catatan termasuk judul, konten, dan item pembelajaran.',
      user_edit_learning_corner: 'Edit catatan learning corner yang sudah ada. Perbarui informasi catatan termasuk judul, konten, dan item pembelajaran sesuai kebutuhan.',
      admin_dashboard: 'Dashboard admin untuk mengelola seluruh sistem. Lihat statistik, kelola user, project, sertifikat, dan angkatan dari satu tempat.',
      admin_learning_corner: 'Kelola semua postingan Learning Corner dari mahasiswa. Lihat, edit, atau hapus catatan pembelajaran sesuai kebutuhan.',
      manage_angkatan: 'Kelola semua angkatan yang terdaftar dalam sistem. Lihat detail angkatan, tambah angkatan baru, edit, atau hapus angkatan sesuai kebutuhan.',
      admin_projects: 'Kelola semua proyek yang terdaftar dalam sistem. Lihat detail proyek, edit, atau hapus proyek sesuai kebutuhan.',
      admin_sertifikat: 'Kelola semua sertifikat yang terdaftar dalam sistem. Lihat detail sertifikat, edit, atau hapus sertifikat sesuai kebutuhan.',
    },
    dosen_dashboard: {
      dashboard_dosen: 'Dashboard Dosen',
      ttl_mhs_bbg: 'Mahasiswa Bimbingan',
      approval_pending: 'Menunggu Persetujuan',
      ttl_pjt: 'Total Project',
      quick_mn: 'Menu Cepat',
      info: 'Informasi',
      info_jrs: 'Prodi:',
      info_jrs: 'Prodi:',
      info_agkt: 'Angkatan:',
      info_khl: 'Keahlian:',
      kll_mhs: 'Kelola Mahasiswa',
      kll_desc_mhs: 'Setujui atau tolak pengajuan mahasiswa',
      kll_pjt: 'Kelola Project',
      kll_desc_pjt: 'Lihat dan validasi semua project yang berjalan',
      kll_srtfkt: 'Kelola Sertifikat',
      kll_desc_srtfkt: 'Lihat dan validasi sertifikat mahasiswa',
    },
    dosen_kll_mhs: {
      kll_mhs: 'Kelola Pengguna',
      kll_desc_mhs: 'Kelola semua mahasiswa yang terdaftar',
      add_mhs: 'Tambah Pengguna',
      pjt: 'Proyek',
      lrn: 'Learning',
      stk: 'Sertifikat',
      acc: 'Diterima',
      rej: 'Ditolak',
      pend: 'Menunggu',
      agkt: 'Angkatan',
    },
    dosen_add_mhs: {
      add_mhs: 'Tambah Mahasiswa Baru',
      add_mhs_desc: 'Form tambah mahasiswa untuk dosen',
      info_mhs: 'Informasi Mahasiswa',
      nm_lgkp: 'Nama Lengkap',
      usn: 'Username',
      email: 'Email',
      klmn: 'Jenis Kelamin',
      klmn_choose: 'Pilih Jenis Kelamin',
      lk: 'Laki-laki',
      pr: 'Perempuan',
      secret: 'Tidak ingin memberi tahu',
      pw: 'Kata Sandi',
      pw_conf: ' Konfirmasi Kata Sandi',
      pfp: 'Foto Profil',
      pfp_format: 'Format: JPEG, PNG, JPG. Maks: 2MB',
      add: 'Tambah Mahasiswa',
      cancel: 'Batal',
    },
    dosen_kll_pjt: {
      ttl_pjt: 'Proyek Mahasiswa',
      desc_pjt: 'Beberapa Pameran Proyek Mahasiswa',
      del_select: 'Hapus Terpilih',
      add_pjt: 'Tambah Proyek',
      empty_pjt: 'Belum ada proyek yang ditampilkan.',
      empty_pjt_desc: 'Silahkan tambahkan proyek baru untuk memulai.',
      det_pjt: 'Detail',
      del_pjt: 'Hpus',
      post_at: 'Diposting',
    },
    dosen_add_pjt: {
      ttl_form: 'Tambah Proyek Mahasiswa Baru',
      desc_form: 'Admin dapat membantu membuat dan mengisi portofolio project mahasiswa',
      filter: 'Filter Mahasiswa',
      empty_filter: 'Tidak ada mahasiswa ditemukan',
      empty_filter_desc: 'Coba ubah filter pencarian anda',
      agkt: 'Angkatan',
      all_agkt: 'Semua Angkatan',
      jrs: 'Jurusan',
      all_jrs: 'Semua Jurusan',
      khl: 'Keahlian',
      all_khl: 'Semua Keahlian',
      trp_filter: 'Terapkan Filter',
      nm_pjt: 'Nama Proyek',
      desc_pjt: 'Deskripsi (opsional)',
      own_pjt: 'Pemilik Proyek (owner)',
      pick: 'Pilih',
      mhs: 'Mahasiswa',
      agkt: 'Angkatan',
      jrs: 'Jurusan',
      act: 'Aksi',
      see: 'Lihat',
      collab: 'Mode Kolaboratif',
      desc_collab: 'Jika dimatikan, rekan project tidak ditampilkan dan tugas hanya mengambil Owner + Leader.',
      add_task: 'Tambah Tugas',
      add_task_opt: 'Tambah Tugas (opsional)',
      rsp_task: 'Penanggung Jawab',
      pick_rsp: '-- Pilih Penanggung Jawab --',
      nm_task: 'Nama Tugas',
      del: 'Hapus',
      add_partner: 'Tambah Rekan (opsional)',
      add_partner_choose: '-- Pilih Mahasiswa --',
      add_partner_btn: '+ Tambah Rekan',
      date_start: 'Tanggal Mulai',
      date_end: 'Tanggal Selesai (opsional)',
      link_pjt: 'Link Proyek (opsional)',
      link_github: 'Link GitHub (opsional)',
      link_vid: 'Link Video (YouTube, opsional)',
      cancel: 'Batal',
      save_pjt: 'Simpan Proyek',
      upd_pjt: 'Perbarui Proyek'
    },
    dosen_sidebar: {
      mhs_bbg: 'Mahasiswa Bimbingan',
      see_mhs: 'Lihat Mahasiswa',
      add_mhs: 'Tambah Mahasiswa',
      pjt_bbbg: 'Proyek Bimbingan',
      see_pjt: 'Lihat Proyek',
      add_pjt: 'Tambah Proyek',
      stk_bbg: 'Sertifikat Bimbingan',
      see_stk: 'Lihat Sertifikat',
      add_stk: 'Tambah Sertifikat',
    },

    dosen_stk: {
      ttl_stk: 'Kelola Semua Sertifikat',
      desc_stk: 'Kelola Semua Sertifikat Milik Mahasiswa',
      add_stk: 'Tambah Sertifikat',
      del_sel: 'Hapus Terpilih',
      srch: 'Pencarian',
      agkt: 'Angkatan',
      all_agkt: 'Semua Angkatan',
      jrs: 'Jurusan',
      all_jrs: 'Semua Jurusan',
      skill: 'Keahlian',
      all_skill: 'Semua Keahlian',
      stat: 'Status',
      all_stat: 'Semua Status',
      trp_filter: 'Terapkan Filter',
      empty_stk: 'Tidak ada sertifikat yang ditemukan.',
      empty_filter: 'Coba atur ulang fitur pencarian anda.',
      desc_empty_stk: 'Mulai tambahkan sertifikat pertama!',
      reset_all: 'Reset Semua Filter',
      sel_all: 'Pilih Semua',
      show: 'Menampilkan',
      from: 'dari',
      stk: 'sertifikat',
      total_pick: 'Total dipilih:',
      nm_stk: 'Nama Sertifikat:',
      nm_mhs: 'Nama Mahasiswa:',
      see_stk: 'Lihat Sertifikat',
      desc: 'Keterangan:',
      stat_ajuan: 'Status Pengajuan:',
      stat_active: 'Status Aktif:',
      added: 'Ditambahkan:',
      del: 'Hapus',
      acc: 'Terima',
      rej: 'Tolak',
    },

    dosen_stk_add: {
      ttl_stk: 'Tambah Sertifikat Baru',
      desc_stk: 'Tambahkan sertifikat yang diperoleh mahasiswa untuk melengkapi portofolio mereka.',
      filter: 'Filter Mahasiswa',
      agkt: 'Angkatan',
      all_agkt: 'Semua Angkatan',
      jrs: 'Jurusan',
      all_jrs: 'Semua Jurusan',
      skill: 'Keahlian',
      all_skill: 'Semua Keahlian',
      trp_filter: 'Terapkan Filter',
      pick_mhs: 'Pilih Mahasiswa',
      pick: 'Pilih',
      nm_mhs: 'Nama Mahasiswa',
      empty_filter: 'Tidak ada mahasiswa ditemukan',
      empty_filter_desc: 'Coba ubah filter pencarian Anda.',
      nm_stk: 'Nama Sertifikat',
      lembaga: 'Lembaga Penerbit',
      launch_date: 'Tanggal Terbit',
      desc_launch: 'Maksimal tanggal hari ini',
      ttl_file: 'Upload File Sertifikat',
      up_file: 'Upload File',
      or_drag: 'Atau Drag and Drop',
      format_file: 'Format yang diperbolehkan, JPG, JPEG, PNG, dan GIF. Maksimal ukuran file 5MB.',
      uped_file: 'File yang diupload akan tersimpan dan dapat diakses melalui link publik.',
      cancel: 'Batal',
      sv_stk: 'Simpan Sertifikat'
    },

    dosen_stk_edit: {
      ttl_form: 'Edit Sertifikat',
      desc_form: 'Perbarui informasi sertifikat yang sudah kamu peroleh.',
      err: 'Terdapat kesalahan pada input:',
      nm_stk: 'Nama Sertifikat',
      lembaga: 'Lembaga Penerbit',
      tggl_terbit: 'Tanggal Terbit',
      maks_tggl: 'Maksimal tanggal hari ini',
      curr_file: 'File saat ini:',
      see_file: 'Lihat file saat ini',
      change_file: 'Ganti File',
      up_file: 'Upload file',
      up_file_opt: 'Upload File (opsional)',
      or_drag: 'atau drag and drop',
      format_file: 'PNG, JPG, GIF up to 5MB',
      allowed_format: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      uped_file: 'File yang diupload akan menggantikan file lama. File lama otomatis akan dihapus',
      cancel: 'Batal',
      upd_stk: 'Update Sertifikat'
    },

    stk_admin_edit: {
      ttl_edit: 'Edit Sertifikat',
      back: 'Kembali',
      nm_stk: 'Nama sertifikat',
      lembaga: 'Lembaga Penerbit',
      launch_date: 'Tanggal Terbit',
      desc_launch: 'Maksimal tanggal hari ini.',
      file_stk: 'File Sertifikat',
      curr_file: 'File saat ini:',
      see_file: 'Lihat file saat ini',
      gnt_stk: 'Ganti file',
      prev_file: 'File saat ini',
      uped_file: 'File yang diupload akan menggantikan file lama. File lama akan otomatis dihapus.',
      up_file: 'Upload file',
      or_drag: 'atau drag and drop',
      format_file: 'PNG, JPG, GIF up to 5MB',
      allowed_format: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      upd_stk: 'Perbarui Sertifikat',
      cancel: 'Batal'
    },

    admin: {
      show: 'Menampilkan',
      from: 'dari',
      user: 'pengguna',
      admin_dashboard_title: 'Dashboard Admin',
      admin_dashboard_desc: 'Ringkasan aktivitas sistem dan statistik utama.',
      button_add_user: 'Tambah User',
      title_jurusan: 'Daftar Jurusan',
      tambah_jurusan: 'Tambah Jurusan',
      tambah_jurusan_title: 'Tambah Jurusan Baru',
      nama_jurusan: 'Nama Jurusan',
      nama_jurusan_label: 'Nama Jurusan:',
      nama_jurusan_placeholder: 'Contoh: Teknik Informatika',
      cari_nama_mahasiswa: 'Cari nama mahasiswa...',
      aksi: 'Aksi',
      tidak_ada_data_jurusan: 'Tidak ada data Jurusan',
      edit_jurusan: 'Edit Jurusan',
      hapus_jurusan: 'Hapus Jurusan',
      hapus_jurusan_prompt: 'Apakah Anda yakin ingin menghapus jurusan',
      tambah_keahlian_title : 'Tambah Keahlian Baru',
      delete_selected: 'Hapus Terpilih',
      no: 'No',
      tambah: 'Tambah',
      cancel: 'Batal',
      save: 'Simpan',
      delete: 'Hapus',
      lihat_prodi : 'Lihat Prodi',
      tambah_prodi : 'Tambah Prodi',
      button_user_list: 'Daftar User',
      button_all_projects: 'Semua Proyek',
      button_certificates: 'Sertifikat',
      total_users_title: 'Total Pengguna',
      total_users_desc: 'Jumlah pengguna terdaftar',
      total_students_title: 'Total Mahasiswa',
      total_students_desc: 'Jumlah mahasiswa aktif',
      total_admin_title: 'Total Admin',
      total_admin_desc: 'Akun admin terdaftar',
      total_lecturers_title: 'Total Dosen',
      total_lecturers_desc: 'Akun dosen terdaftar',
      highlight_title: 'Sorotan',
      students_label: 'Mahasiswa',
      projects_label: 'Proyek',
      learning_corners_label: 'Learning Corner',
      certificates_label: 'Sertifikat',
      registered_label: 'terdaftar',
      total_projects_title: 'Total Proyek',
      total_learning_corners_title: 'Total Learning Corner',
      total_certificates_title: 'Total Sertifikat',
      latest_activity_title: 'Aktivitas Terbaru (Proyek, Sertifikat, Learning Corner)',
      latest_activity_desc: 'Lihat aktivitas terbaru di platform',
      see_all: 'Lihat Semua',
      project_no_title: 'Project tanpa judul',
      posted_by: 'Diposting oleh',
      student_label: 'Mahasiswa',
      no_recent_activity: 'Belum ada aktivitas terbaru',
      show_more: 'Tampilkan lagi',
      pending_students_title: 'Mahasiswa Menunggu',
      pending_students_desc: 'Mahasiswa yang sedang menunggu verifikasi akun',
      pending_students_empty: 'Tidak ada mahasiswa dalam status pengajuan.',
      rejected_students_title: 'Mahasiswa Ditolak',
      rejected_students_desc: 'Mahasiswa yang pengajuannya telah ditolak',
      rejected_students_empty: 'Tidak ada mahasiswa ditolak.',
      semua_user: 'Lihat Semua User',
      tambah_user: 'Tambah User',
      lihat_proyek: 'Lihat Proyek',
      tambah_proyek: 'Tambah Proyek',
      lihat_angkatan: 'Lihat Angkatan',
      tambah_angkatan: 'Tambah Angkatan',
      lihat_sertifikat: 'Lihat Sertifikat',
      tambah_sertifikat: 'Tambah Sertifikat',
      tambah_user: 'Tambah User Baru',
      pilih_role: 'Pilih role user yang akan ditambahkan',
      role_admin: 'Admin',
      desc_admin: 'Hak akses penuh untuk mengelola sistem',
      form_admin: 'Form Sederhana',
      role_mhs: 'Mahasiswa',
      desc_mhs: 'Akses untuk mengikuti kegiatan akademik',
      form_mhs: 'Form Lengkap',
      role_dosen: 'Dosen',
      desc_dosen: 'Akses untuk mengelola pembelajaran',
      form_dosen: 'Form Lengkap',
      info: 'Informasi Dasar',
      nm_lgkp: 'Nama Lengkap',
      lihat_keahlian : 'Lihat Keahlian',
      usrnm: 'Nama Pengguna',
      usrnm_error: 'Hanya huruf, angka, dan underscore (_)',
      email: 'Email',
      pw: 'Kata Sandi',
      pw_confirm: 'Konfirmasi Kata Sandi',
      pfp: 'Foto Profil',
      pfp_error: 'Format: JPEG, PNG, JPG. Maks: 2MB',
      info_lebih: 'Informasi Tambahan',
      jurusan: 'Prodi',
      detail_prodi_title: 'Detail Prodi',
      nama_prodi_label: 'Nama Prodi',
      total_mahasiswa: 'Total Mahasiswa',
      statistik_mahasiswa: 'Statistik Mahasiswa',
      grafik_status_mahasiswa: 'Grafik Status Mahasiswa',
      daftar_mahasiswa: 'Daftar Mahasiswa',
      cari_nama_mahasiswa: 'Cari nama mahasiswa...',
      tidak_ada_mahasiswa_prodi: 'Tidak ada mahasiswa dalam prodi ini.',
      opt_jurusan: 'Pilih Prodi',
      jurusan: 'Prodi',
      detail_prodi_title: 'Detail Prodi',
      nama_prodi_label: 'Nama Prodi',
      total_mahasiswa: 'Total Mahasiswa',
      statistik_mahasiswa: 'Statistik Mahasiswa',
      grafik_status_mahasiswa: 'Grafik Status Mahasiswa',
      daftar_mahasiswa: 'Daftar Mahasiswa',
      cari_nama_mahasiswa: 'Cari nama mahasiswa...',
      tidak_ada_mahasiswa_prodi: 'Tidak ada mahasiswa dalam prodi ini.',
      opt_jurusan: 'Pilih Prodi',
      keahlian: 'Bidang Keahlian',
      opt_keahlian: 'Pilih Keahlian',
      angkatan: 'Angkatan',
      opt_angkatan: 'Pilih Angkatan',
      cncl: 'Batal',
      tambah: 'Tambah User',
      // Halaman lihat semua user
      kll_pengguna: 'Kelola Pengguna',
      desc_kll_pengguna: 'Kelola semua pengguna yang terdaftar.',
      del_user: 'Hapus Terpilih',
      add_user: 'Tambah Pengguna',
      srch_usr: 'Pencarian',
      search_placeholder: 'Cari berdasarkan nama, username, atau email..',
      role_usr: 'Role',
      role_usr1: 'Semua Role',
      stat_acc: 'Status Akun',
      stat_pengajuan: 'Status Pengajuan',
      stat_diterima: 'Di terima',
      stat_ditolak: 'Di tolak',
      stat_aktif: 'Aktif',
      stat_non_aktif: 'Non Aktif',
      all_stat: 'Semua Status',
      reset_filter: 'Reset Filter',
      trp_filter: 'Terapkan Filter',
      plh_semua: 'Pilih Semua',
      total_dipilih: 'Total dipilih:',
      tbl_foto: 'Foto',
      tbl_nm: 'NAMA / USERNAME',
      tbl_email: 'EMAIL',
      tbl_role: 'ROLE',
      tbl_stat: 'STATUS',
      tbl_jrs: 'JURUSAN',
      tbl_agkt: 'ANGKATAN',
      tbl_act: 'AKSI',
      //Halmaan tambah user
      info_adduser: 'Informasi Dasar',
      nm_lgkp: 'Nama Lengkap',
      usr_req: 'Hanya huruf, angka, dan underscore (_)',
      pw_adduser: 'Kata Sandi',
      pw_confirm_adduser: 'Konfirmasi Kata Sandi',
      add_addusr: 'Tambah User',
      cancel_addusr: 'Batal',
      more_info_addusr: 'Informasi Tambahan',
      jrs_addusr: 'Jurusan',
      chs_jrs_addusr: 'Pilih Jurusan',
      exp_addusr: 'Bidang Keahlian',
      chs_exp_addusr: 'Pilih Bidang Keahlian',
      agkt_addusr: 'Angkatan',
      chs_agkt_addusr: 'Pilih Angkatan',
      //Edit user (menggunakan form yang sama dengan halaman tambah user, hanya data tambahan yang belum)
      back: 'Kembali',
      pw_new: 'Kata Sandi Baru (kosongkan jika tidak diubah)',
      pw_new_confirm: 'Konfirmasi Kata Sandi Baru',
      pfp_new: 'Foto Profil',
      pfp_frmt: 'Format: JPEG, PNG, JPG. Maks: 2MB',
      save_new: 'Simpan Perubahan',
      //Halaman project manajemen
      delete_select: 'Hapus Terpilih',
      select_all: 'Pilih Semua',
      selected: 'Terpilih:',
      empty_project: 'Belum ada proyek yang di tampilkan.',
      desc_empty_project: 'Silahkan tambahkan proyek baru untuk memulai.',
      edit_project: 'Edit',
      delete_project: 'Hapus',
      //Halaman Create Project
      filter_mhs: 'Filter Mahasiswa',
      all_cohorts: 'Semua Angkatan',
      all_jrs: 'Semua Jurusan',
      all_skill: 'Semua Keahlian',
      nm_project: 'Nama Project',
      desc_project: 'Deskripsi (opsional)',
      leader_project: 'Pilih Mahasiswa (Pemimpin Project)',
      tbl_pjt_1: 'PILIH',
      tbl_pjt_2: 'MAHASISWA',
      tbl_pjt_3: 'ANGKATAN',
      tbl_pjt_4: 'PRODI',
      tbl_pjt_4: 'PRODI',
      tbl_pjt_5: 'KEAHLIAN',
      tbl_pjt_6: 'AKSI',
      act_tbl: 'Lihat',
      empty_filter: 'Tidak ada mahasiswa ditemukan',
      empty_filter_desc: 'Coba ubah filter pencarian anda',
      partner_project: 'Tambah Rekan (opsional)',
      partner_choice: '-- Pilih Rekan Project --',
      add_partner: 'Tambah Rekan',
      date_start: 'Tanggal Mulai',
      date_end: 'Tanggal Selesai (opsional)',
      date_end_must: 'Tanggal Selesai',
      //Halaman edit proyek
      title_edit: 'Edit Project',
      desc_edit: 'Edit informasi project atau ganti file jika diperlukan. Pastikan untuk menyimpan perubahan setelah selesai.',
      //Halaman tambah angkatan
      title_agkt: 'Daftar Angkatan',
      add_agkt: 'Tambah Angkatan',
      no_agkt: 'NO',
      nm_agkt: 'NAMA ANGKATAN',
      thn_agkt: 'TAHUN MASUK',
      exit_agkt: 'TAHUN KELUAR',
      total_mhs: 'TOTAL MAHASISWA',
      aksi_agkt: 'AKSI',
      //Halaman detail angkatan
      detail_agkt: 'Detail Angkatan',
      nm_agkt_kcl: 'Nama Angkatan',
      thn_agkt_kcl: 'Tahun Masuk',
      exit_agkt_kcl: 'Tahun Keluar',
      mhs_stats: 'Statistik Mahasiswa',
      total_mhs_agkt: 'Total Mahasiswa',
      list_mhs: 'Daftar Mahasiswa',
      no_agkt_mhs: 'NO',
      nm_mhs_agkt: 'NAMA',
      jrs_agkt: 'PRODI',
      jrs_agkt: 'PRODI',
      stat_agkt: 'STATUS',
      ///halaman tambah angkatan
      add_agkt: 'Tambah Angkatan Baru',
      desc_agkt_exit: 'Kosongkan jika belum lulus',
      addadd_agkt: 'Tambahkan Angkatan',
      //Halaman kelola sertifikat
      title_srtfkt: 'Kelola Semua Sertifikat',
      desc_srtfkt: 'Kelola Semua Sertifikat Milik Mahasiswa',
      empty_srtfkt: 'Tidak ada sertifikat yang ditemukan.',
      empty_desc_srtfkt: 'Mulai tambahkan sertifikat yang pertama!',
      add_srtfkt: 'Tambah Sertifikat',
      stat_filter: 'Status',
      stat_filter_all: 'Semua Status',
      tmplkn: 'Menampilkan',
      dr: 'dari',
      srtfkt: 'sertifikat',
      nm_srtfkt: 'Nama Sertifikat:',
      nm_mhs_srtfkt: 'Nama Mahasiswa:',
      stat_active: 'Status Aktif',
      edit_srtfkt : 'Edit Sertifikat',
      hapus_srtfkt: 'Hapus Sertifikat',
      //halaman menambah sertifikat baru
      title_srtfkt_create: 'Tambah Sertifikat Baru',
      desc_srtfkt_create: 'Tambahkan sertifikat yang diperoleh mahasiswa untuk melengkapi portofolio mereka.',
      pilih_mhs: 'Pilih Mahasiswa',
      nm_mhs: 'Nama Mahasiswa',
      see_profile: 'Lihat Profil →',
      nm_srtfkt_create: 'Nama Sertifikat',
      lembaga_penerbit: 'Lembaga Penerbit',
      tggl_terbit: 'Tanggal Terbit',
      max_tggl: 'Maksimal tanggal hari ini',
      upload_srtfkt: 'Upload File Sertifikat',
      up_file: 'Upload File',
      or_drag: 'atau drag and drop',
      format_srtfkt: 'PNG, JPG, GIF, Maksimal 5MB',
      save_srtfkt: 'Simpan Sertifikat',
      // Keahlian management
      title_keahlian: 'Daftar Keahlian',
      nama_keahlian: 'Nama Keahlian',
      nama_keahlian_label: 'Nama Keahlian',
      nama_keahlian_placeholder: 'Contoh: Web Development',
      tambah_keahlian: 'Tambah Keahlian',
      detail_keahlian_title: 'Detail Keahlian',
      tambah_jurusan_title: 'Tambah Keahlian Baru',
      nama_jurusan_label: 'Nama Keahlian',

    },

    dashboard: {
      postingan_kosong: 'Belum ada postingan acak untuk ditampilkan saat ini',
      total_mahasiswa: 'Total Seluruh Mahasiswa',
      semua_learning_corner: 'Semua Learning Corner',
      total_project: 'Total Semua Project',
      total_sertifikat: 'Total Semua Sertifikat',
      perihal_terbaru: 'Postingan Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'Sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
      ttl_pjt: 'Proyek',
      ttl_stk: 'Sertifikat',
      ttl_lrn: 'Learning Corner',
      empty_lrn: 'Belum ada learning corner.',
      empty_pjt: 'Belum ada postingan proyek.',
      empty_stk: 'Belum ada sertifikat.'
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Project Dikerjakan',
      total_sertifikat: 'Total Sertifikat Didapat',
      perihal_terbaru: 'Postingan Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
    },
    project: {
      project_saya: 'Project Saya',
      deskripsi: 'Kelola project milikmu, yang kamu pimpin, dan yang kamu ikuti sebagai anggota tim.',
      tambah_project: 'Tambah Project Baru',
      edit_project: 'Edit Project',
      hapus_project: 'Hapus Project',
      pemilik: 'Pemilik',
      leader: 'Leader',
      anggota: 'Anggota',
      no_project: 'Belum ada project yang terkait dengan akunmu.',
      dibuat_oleh: 'Dibuat oleh',
      mulai: 'Mulai',
      selesai: 'Selesai',
      lihat_project: 'Lihat Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      tambah_project: 'Tambah Project Baru',
      edit_project: 'Edit Project',
      edit_project: 'Edit Project',
      desc_create: 'Tambah project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
      // Detail Angkatan
      nm_agkt: 'Nama Angkatan',
      thn_msk: 'Tahun Masuk',
      thn_klr: 'Tahun Keluar',
      blm_ttk: 'Belum ditentukan',
      stat_mhs: 'Statistik Mahasiswa',
      ttl_mhs: 'Total Mahasiswa',
      aktf: 'Aktif',
      tdk_aktf: 'Tidak Aktif',
      grfk_stat_mhs: 'Grafik Status Mahasiswa',
      dft_mhs: 'Daftar Mahasiswa',
      flt_pencarian: 'Filter & Pencarian',
      cri_nm_mhs: 'Cari nama mahasiswa...',
      flt_jrs: 'Filter Prodi',
      smw_jrs: 'Semua Prodi',
      flt_jrs: 'Filter Prodi',
      smw_jrs: 'Semua Prodi',
      flt_stat: 'Filter Status',
      smw_stat: 'Semua Status',
      rst_flt: 'Reset Filter',
      trp_flt: 'Terapkan Filter',
      tmpilkan: 'Menampilkan',
      no: 'No',
      nm_mhs: 'Nama Mahasiswa',
      jrs: 'Jurusan',
      eml: 'Email',
      stat: 'Status',
      aksi: 'Aksi',
      tdk_ada_mhs_ttm: 'Tidak ada mahasiswa ditemukan',
      cba_ubh_flt: 'Coba ubah filter pencarian Anda atau cari dengan kata kunci lain',
      tdk_ada_mhs_angkt: 'Tidak ada mahasiswa dalam angkatan ini.',
      lht: 'Lihat',
      // Detail Angkatan
      nm_agkt: 'Nama Angkatan',
      thn_msk: 'Tahun Masuk',
      thn_klr: 'Tahun Keluar',
      blm_ttk: 'Belum ditentukan',
      stat_mhs: 'Statistik Mahasiswa',
      ttl_mhs: 'Total Mahasiswa',
      aktf: 'Aktif',
      tdk_aktf: 'Tidak Aktif',
      grfk_stat_mhs: 'Grafik Status Mahasiswa',
      dft_mhs: 'Daftar Mahasiswa',
      flt_pencarian: 'Filter & Pencarian',
      cri_nm_mhs: 'Cari nama mahasiswa...',
      flt_jrs: 'Filter Jurusan',
      smw_jrs: 'Semua Jurusan',
      flt_stat: 'Filter Status',
      smw_stat: 'Semua Status',
      rst_flt: 'Reset Filter',
      trp_flt: 'Terapkan Filter',
      tmpilkan: 'Menampilkan',
      no: 'No',
      nm_mhs: 'Nama Mahasiswa',
      jrs: 'Jurusan',
      eml: 'Email',
      stat: 'Status',
      aksi: 'Aksi',
      tdk_ada_mhs_ttm: 'Tidak ada mahasiswa ditemukan',
      cba_ubh_flt: 'Coba ubah filter pencarian Anda atau cari dengan kata kunci lain',
      tdk_ada_mhs_angkt: 'Tidak ada mahasiswa dalam angkatan ini.',
      lht: 'Lihat',
    },
    project_edit: {
      title: 'Edit Project',
      desc: 'Edit informasi project atau ganti file jika diperlukan. Pastikan untuk menyimpan perubahan setelah selesai.',
      filter_mhs: 'Filter Mahasiswa',
      angkatan: 'Angkatan',
      jurusan: 'Jurusan',
      keahlian: 'Keahlian',
      semua_angkatan: 'Semua Angkatan',
      semua_jurusan: 'Semua Jurusan',
      semua_keahlian: 'Semua Keahlian',
      reset_filter: 'Reset Filter',
      apply_filter: 'Terapkan Filter',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      leader_project: 'Pilih Mahasiswa (Pemimpin Project)',
      selected_leader_prefix: 'Pemimpin:',
      leader_search_placeholder: 'Cari nama pemimpin project...',
      pilih_col: 'Pilih',
      mahasiswa_col: 'Mahasiswa',
      angkatan_col: 'Angkatan',
      jurusan_col: 'Prodi',
      jurusan_col: 'Prodi',
      keahlian_col: 'Keahlian',
      aksi_col: 'Aksi',
      lihat: 'Lihat',
      no_students_found: 'Tidak ada mahasiswa ditemukan',
      change_filter_hint: 'Coba ubah filter pencarian Anda',
      add_member: 'Tambah Rekan (opsional)',
      add_member_btn: '+ Tambah Rekan',
      member_search_placeholder: 'Cari nama rekan...',
      no_students_available: 'Tidak ada mahasiswa tersedia',
      name_unknown: 'Nama Tidak Diketahui',
      select_member_option: '-- Pilih Rekan Project --',
      already_selected_suffix: ' (Sudah dipilih)',
      leader_suffix: ' (Pemimpin)',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      cancel: 'Batal',
      update_project: 'Perbarui Proyek',
    },
    project_detail: {
      detail_project: 'Detail Project',
      desc_detail: 'Lihat detail project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      students_involved: 'Siswa Terlibat',
      tambah_pemimpin: 'Pemimpin Tim',
      no_leader: 'Tidak ada leader',
      tambah_rekan: 'Rekan Rekan Kerja',
      no_member: 'Tidak ada rekan',
      time_period: 'Periode Waktu',
      links: 'Link',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Hapus Terpilih',
      add_new_note: '+ Tambah Catatan Baru',
      no_learning_corner: 'Belum ada catatan Learning Corner di project ini.',
      select_to_delete: 'Pilih untuk dihapus',
      edit: 'Edit',
      delete: 'Hapus',
      status_incoming: 'Akan Datang',
      status_present: 'Sedang Berjalan',
      status_past: 'Selesai',
      progress_done: 'Selesai',
    },
    portofolio_user: {
      portfolio: 'Portfolio',
      prodi: 'Prodi :',
      agkt: 'Angkatan',
      khl: 'Keahlian',
      Utama: 'Utama',
      pjt: 'Proyek',
      done: 'Selesai',
      ongoing: 'Sedang Dikerjakan',
      soon: 'Akan Datang',
      show_done: 'Menampilkan proyek yang telah selesai',
      show_ongoing: 'Menampilkan proyek yang sedang dikerjakan',
      show_soon: 'Menampilkan proyek yang akan datang',
      show_all: 'Menampilkan semua proyek',
      pjt_noneownlead: 'Tidak ada owner/Leader',
      pjt_nolead: 'Tidak ada leader',
      pjt_own: 'Pemilik proyek',
      pjt_ownnone: 'Tidak ada owner',
      pjt_noteam: 'Belum ada anggota tim',
      pjt_desc: 'Deskripsi',
      pjt_vidprev: 'Pratinjau Video',

      team: 'Anggota Tim',
      start: 'Mulai',
      end: 'Selesai',
      stk: 'Sertifikat',
      lrn: 'Learning Corner',
      note: 'Catatan',
      empty_content: 'Tidak ada konten yang dapat ditampilkan',
      lrn_origin: 'Dari proyek: ',
      empty_lrn: 'Belum ada learning corner'
    },
    search: {
      search: 'Cari',
      search_placeholder: 'Cari project, sertifikat, atau learning corner...',
      placeholder_student: 'Cari Mahasiswa...',
      placeholder_portfolio: 'Cari Portofolio...',
      placeholder_certificate: 'Cari Sertifikat...',
      filter_jurusan: 'Semua Prodi',
      filter_jurusan: 'Semua Prodi',
      filter_keahlian: 'Semua Keahlian',
      filter_angkatan: 'Semua Angkatan',
    },
    result_search: {
      hasil_pencarian: 'Hasil Pencarian',
      filter_aktif: 'Filter aktif:',
      clr_filter: 'Hapus semua filter',
      mhs: 'Mahasiswa',
      khl: 'Keahlian',
      khl: 'Keahlian',
      tampil: 'Lihat Semua',
      sembunyi: 'Sembunyikan',
      prtfl_lengkap: 'Lihat portofolio lengkap →',
      sertifikat: 'Sertifikat',
      none: 'Tidak ada hasil yang ditemukan',
      none_desc: 'Coba ubah kata kunci, pilih jurusan/keahlian/angkatan lain, atau hapus filter di atas.',
      empty_link: 'Tidak ada link project',
      oleh: 'Oleh',
      see_project: 'Lihat Project →'
    },
    sidebar: {
      dashboard: 'Beranda',
      dashboard_nonuser: 'Beranda',
      my_dashboard: 'My Dashboard',
      admin_dashboard: 'Admin Dashboard',
      manajemen_users: 'Manajemen User',
      semua_user: 'Lihat Semua User',
      tambah_user: 'Tambah User',
      lihat_proyek: 'Lihat Proyek',
      tambah_proyek: 'Tambah Proyek',
      lihat_angkatan: 'Lihat Angkatan',
      tambah_angkatan: 'Tambah Angkatan',
      lihat_sertifikat: 'Lihat Sertifikat',
      tambah_sertifikat: 'Tambah Sertifikat',
      manajemen_projects: 'Manajemen Project',
      manajemen_sertifikat: 'Manajemen Sertifikat',
      manajemen_angkatan: 'Manajemen Angkatan',
      manajemen_prodi: 'Manajemen Prodi',
      lihat_prodi: 'Lihat Prodi',
      tambah_prodi: 'Tambah Prodi',
      manajemen_keahlian: 'Manajemen Keahlian',
      lihat_keahlian: 'Lihat Keahlian',
      tambah_keahlian: 'Tambah Keahlian',
      dashboard_dosen: 'Dashboard Dosen',
      mahasiswa_bimbingan: 'Mahasiswa Bimbingan',
      projects_bimbingan: 'Projects Bimbingan',
      sertifikat_bimbingan: 'Sertifikat Bimbingan',
      project_mahasiswa: 'Project Mahasiswa',
      project_mahasiswa_saya: 'Project Saya',
      project_mahasiswa_saya_tambah: 'Tambah Project Baru',
      sertifikat_mahasiswa: 'Sertifikat Mahasiswa',
      sertifikat_mahasiswa_saya: 'Sertifikat Saya',
      sertifikat_mahasiswa_saya_tambah: 'Tambah Sertifikat',
      corner_mahasiswa: 'Corner Mahasiswa',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Bahasa',
      logout: 'Logout',
      login: 'Masuk',
      login_prompt: 'Kamu Mahasiswa? Login Sekarang!',
      register: 'Register',
    },
    footer: {
      footer_rights: '© Portofolio Mahasiswa 2026. Semua hak dilindungi undang-undang.',
    },
    project_user: {
      project_user_title: 'Project ',
      project_user_desc: 'Daftar project yang kamu ikuti sebagai anggota.',
      nama_project: 'Nama Project',
      tanpa_nama_project: "Tanpa Nama Project",
      tidak_diketahui: "Tidak diketahui",
      selesai: "Selesai",
      sedang_berjalan: "Sedang Berjalan",
      akan_datang: "Akan Datang",
      sekarang: "Sekarang",
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
      diposting: 'Diposting',
      no_thumbnail_text: 'Tidak ada thumbnail tersedia',
      no_thumbnail_description: 'Tambahkan link video dengan benar',
    },
    sertifikat: {
      sertifikat_title: 'Sertifikat Saya',
      sertifikat_desc: 'Kelola semua sertifikat yang kamu miliki di sini.',
      sertifikat_create_button: 'Tambah Sertifikat Baru',
      sertifikat_no_data: 'Belum ada sertifikat.',
      sertifikat_no_data_description: 'Mulai tambahkan sertifikat pertama kamu!',
      sertifikat_link: 'Lihat Sertifikat',
      sertifikat_dibuat: 'Ditambahkan',
      sertifikat_diupdate: 'Diperbarui',
      edit_button: 'Edit',
      delete_button: 'Hapus',
    },

    sertifikat_user: {
      sertifikat_title: 'Sertifikat Saya',
      sertifikat_desc: 'Kelola semua sertifikat yang kamu miliki di sini.',
      sertifikat_mahasiswa_title: 'Sertifikat Mahasiswa',
      sertifikat_mahasiswa_desc: 'Lihat sertifikat mahasiswa',
      sertifikat_create_button: 'Tambah Sertifikat Baru',
      sertifikat_no_data: 'Belum ada sertifikat.',
      sertifikat_no_data_description: 'Mulai tambahkan sertifikat pertama kamu!',
      sertifikat_link: 'Lihat Sertifikat',
      sertifikat_dibuat: 'Ditambahkan',
      sertifikat_diupdate: 'Diperbarui',
    },

    sertifikat_create: {
      sertifikat_create_title: 'Tambah Sertifikat Baru',
      sertifikat_create_desc: 'Tambahkan sertifikat yang kamu peroleh untuk melengkapi portofoliomu.',
      nama_sertifikat: 'Nama Sertifikat',
      error_global_title: 'Terdapat kesalahan pada input:',
      tanggal_terbit: 'Tanggal Terbit',
      lembaga_penerbit: 'Lembaga Penerbit',
      upload_file_sertifikat: 'Upload File Sertifikat',
      max_date: 'Maksimal tanggal hari ini',
      upload_file: 'Upload File',
      or_drag_drop: 'atau drag and drop',
      upload_file_desc: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      upload_file_tips: 'File yang diupload akan tersimpan dan dapat diakses melalui link publik.',
      cancel: 'Batal',
      save: 'Simpan Sertifikat'

    },

    sertifikat_edit: {
      sertifikat_edit_title: 'Edit Sertifikat',
      sertifikat_edit_desc: 'Perbarui informasi sertifikat yang kamu miliki.',
      error_global_title: 'Terdapat kesalahan pada input:',
      nama_sertifikat: 'Nama Sertifikat',
      lembaga_penerbit: 'Lembaga Penerbit',
      tanggal_terbit: 'Tanggal Terbit',
      max_date: 'Maksimal tanggal hari ini',
      upload_file_sertifikat: 'Upload File Sertifikat',
      replace_file: 'Ganti File',
      upload_file: 'Upload File',
      or_drag_drop: 'atau drag and drop',
      current_file: 'File Saat Ini',
      view_current_file: 'Lihat File Saat Ini',
      upload_file_desc: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      upload_file_tips: 'File yang diupload akan tersimpan dan dapat diakses melalui link publik.',
      new_file_preview: 'Preview File Baru:',
      current_file_preview: 'File Saat Ini:',
      additional_info: 'File yang diupload akan menggantikan file lama. File lama akan otomatis dihapus.',
      cancel: 'Batal',
      update_sertifikat: 'Perbarui Sertifikat',
    },
    kelola_user: {
      kelola_user_title: 'Kelola Users',
      kelola_user_desc: 'Tambah, edit, atau hapus user di sistem.',
      status_diterima: 'Diterima',
      status_ditolak: 'Ditolak',
      status_sedang_di_ajukan: 'Sedang Di Ajukan',
      tambah_user: 'Tambah User',
      edit_user: 'Edit User',
      hapus_user: 'Hapus User',
      sertifikat_title: 'Sertifikat',
      aksi: 'Aksi',
    },
    kelola_project: {
      kelola_project_title: 'Kelola Projects',
      kelola_project_desc: 'Tambah, edit, atau hapus project di sistem.',
      tambah_project: 'Tambah Project',
      edit_project: 'Edit Project',
      hapus_project: 'Hapus Project',
      nama_project: 'Nama Project',
      deskripsi: 'Deskripsi',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai',
      link_project: 'Link Project',
      link_github: 'Link GitHub',
      link_video: 'Link Video',
      diposting: 'Diposting',
    },
    kelola_create_project: {
      kelola_create_project_title: 'Tambah Project',
      kelola_create_project_desc: 'Tambah project yang pernah dibuat oleh mahasiswa.',
      nama_project: 'Nama Project',

    },

  },
  en: {
    msh_project_task: {
      add_task: 'Add Task',
      add: 'Add task',
      rsp_task: 'Responsible Person',
      nm_task: 'Task Name',
      pick_rsp: '-- Pick Responsible Person --',
    },

    msh_lrn_add: {
      ttl_form: 'Add new notes',
      desc_form: 'Write what you have learnt today or knowledge that you want to share.',
      ttl_lrn: 'Note Title',
      add_content: 'Additional Content (optional)',
      add_item: 'Add Item',
      del: 'Delete',
      add_text: 'Add Text',
      add_img: 'Image',
      add_link: 'Link/Reference',
      sv_lrn: 'Save Note',
    },

    pjt_detail: {
      edit_project: 'Edit Project',
      desc_pjt: 'Project Description',
      empty_desc: 'There is no description for this project.',
      tm_pjt: 'Project Timeline',
      tm_start: 'Start',
      tm_end: 'Finish',
      tm_none: 'Not Determined',
      own_pjt: 'Owner',
      link_pjt: 'Related Links',
      empty_link: 'There is no related links',
      lead_pjt: 'Project Leader',
      tim_pjt: 'Team Members',
      empty_tim: 'There is no team member',
      lrn_pjt: 'Learning Corner',
      desc_lrn_pjt: 'Notes and project documentation',
      empty_lrn: 'There is no learning corner yet',
      desc_empty_lrn: 'Start adding the first notes for this project',
      del_sel: 'Delete Selected',
      sel_del: 'Pick some to delete',
      del: 'Delete',
      add_lrn: 'Add Note'
    },

    popup: {
      dashboard: 'Manage your dashboard here. Monitor activities and latest projects.',
      portofolio_saya: 'View your portfolio showcasing all projects, certificates, and learning corners you have created.',
      project_saya: 'Manage all your projects here. Add, edit, or delete projects to complete your portfolio.',
      sertifikat_saya: 'Manage your certificates here. Add new certificates from various institutions to enhance your credibility.',
      learning_corner_saya: 'Manage your learning corner here. Share knowledge and experiences you have learned with the community.',
      profile_saya: 'Edit your profile to display personal information, bio, and an attractive profile picture.',
      semua_portofolio: 'Explore portfolios from other students. See various projects, certificates, and their achievements.',
      semua_project: 'View all projects published by the community. Inspiration and collaboration start here.',
      semua_sertifikat: 'View certificates from various students. Learn and get inspired by their achievements.',
      semua_learning_corner: 'Access learning corners from across the community. Share and learn valuable experiences from fellow students.',
      add_angkatan: 'Add new cohort to the system. Manage student cohorts effectively for better organization and tracking.',
      edit_angkatan: 'Edit existing cohort information. Update details to keep the cohort data accurate and up-to-date.',
      detail_angkatan: 'View detailed information about a specific cohort. See student statistics and manage cohort-related activities.',
      add_project: 'Add a new project for students. Admin can help create and manage student project portfolios with complete information.',
      edit_project: 'Edit existing project information. Update project details, team members, or files as needed.',
      user_edit_project: 'Edit an existing project for a student. Admin can help update and manage student project portfolios with complete information.',
      user_detail_project: 'View detailed information about a student\'s project. See project description, timeline, team members, and related links.',
      add_sertifikat: 'Add a new certificate for students. Select a student and enter certificate information including name, issuing institution, and certificate file.',
      user_create_project: 'Create a new project for a student. Admin can help create and fill portfolio student\'s project.',
      edit_sertifikat: 'Edit existing certificate information. Update certificate name, issuing institution, issue date, or certificate file as needed.',
      user_create_sertifikat: 'Create a new certificate for a student. Select a student and fill in the certificate information including name, issuing institution, issue date, and upload the certificate file.',
      user_edit_sertifikat: 'Edit an existing certificate for a student. Update the certificate information including name, issuing institution, issue date, or replace the certificate file as needed.',
      dosen_add_project: 'Add a new project for students. Lecturers can assist in creating and completing student project portfolios with detailed information.',
      dosen_edit_project: 'Edit existing project information. Update project details, team members, or project files as needed.',
      dosen_add_sertifikat: 'Add a new certificate for students. Lecturers can assist in creating and completing student certificate portfolios with detailed information.',
      dosen_edit_sertifikat: 'Edit existing certificate information. Update certificate details, issuing institution, issuance date, or certificate files as needed.',
      dosen_add_user: 'Add a new user to the system. Select a role (Admin, Student, or Lecturer) and provide complete information for the new user.',
      dosen_edit_user: 'Edit existing user information. Update name, username, email, or role as needed.',
      dosen_learning_corner: 'Manage all student Learning Corner posts. View, edit, or delete learning notes as required.',
      dosen_daftar_mahasiswa: 'Manage all students registered in the system. View student details, approve or reject student submissions, and manage student information as needed.',
      dosen_projects: 'Manage all projects in the system. View project details, add new projects, edit, or delete projects as needed.',
      dosen_certificates: 'Manage all certificates in the system. View certificate details, add new certificates, edit, or delete certificates as needed.',
      add_user: 'Add a new user to the system. Select a role (Admin, Student, or Lecturer) and fill in complete information for the new user.',
      edit_user: 'Edit existing user information. Update name, username, email, or role as needed.',
      manage_users: 'Manage all registered users in the system. View user details, update status, edit information, or delete users as needed.',
      user_create_learning_corner: 'Create a new learning corner note for a student\'s project. Admin can help create and fill learning corner notes for student\'s project.',
      user_edit_learning_corner: 'Edit an existing learning corner note for a student\'s project. Admin can help update and manage learning corner notes for student\'s project.',
      admin_dashboard: 'Admin dashboard to manage the entire system. View statistics, manage users, projects, certificates, and cohorts from one place.',
      admin_learning_corner: 'Manage all Learning Corner posts from students. View, edit, or delete learning notes as needed.',
      manage_angkatan: 'Manage all registered cohorts in the system. View cohort details, add new cohorts, edit, or delete cohorts as needed.',
      admin_projects: 'Manage all projects in the system. View project details, add new projects, edit, or delete projects as needed.',
      admin_sertifikat: 'Manage all certificates in the system. View certificate details, add new certificates, edit, or delete certificates as needed.',
    },
    dosen_dashboard: {
      dashboard_dosen: 'Lecturer Dashboard',
      ttl_mhs_bbg: 'Total Advised Students',
      approval_pending: 'Pending Approval',
      ttl_pjt: 'Total Projects',
      quick_mn: 'Quick Menu',
      info: 'Information',
      info_jrs: 'Majors:',
      info_agkt: 'Cohorts:',
      info_khl: 'Skills:',
      kll_mhs: 'Manage Students',
      kll_desc_mhs: 'Approve or reject student submissions',
      kll_pjt: 'Manage Projects',
      kll_desc_pjt: 'View and validate all ongoing projects',
      kll_srtfkt: 'Manage Certificates',
      kll_desc_srtfkt: 'View and validate student certificates',
    },
    dosen_kll_mhs: {
      kll_mhs: 'Manage Students',
      kll_desc_mhs: 'Manage all students registered in the system',
      add_mhs: 'Add Student',
      pjt: 'Projects',
      lrn: 'Learning',
      stk: 'Certificates',
      acc: 'Accepted',
      rej: 'Rejected',
      pend: 'Pending',
      agkt: 'Cohort',
    },
    dosen_add_mhs: {
      add_mhs: 'Add New Student',
      add_mhs_desc: 'Student addition form for lecturers',
      info_mhs: 'Student Information',
      nm_lgkp: 'Full Name',
      usn: 'Username',
      email: 'Email',
      klmn: 'Gender',
      klmn_choose: 'Select Gender',
      lk: 'Male',
      pr: 'Female',
      secret: 'Prefer not to say',
      pw: 'Password',
      pw_conf: ' Confirm Password',
      pfp: 'Profile Photo',
      pfp_format: 'Format: JPEG, PNG, JPG. Max: 2MB',
      add: 'Add Student',
      cancel: 'Cancel',
    },
    dosen_kll_pjt: {
      ttl_pjt: 'Student Projects',
      desc_pjt: 'Some Showcase of Student\'s Projects',
      del_select: 'Delete Selected',
      add_pjt: 'Add Project',
      empty_pjt: 'No projects to display.',
      empty_pjt_desc: 'Add a new project to get started.',
      del_pjt: 'Delete',
      det_pjt: 'Detail',
      post_at: 'Posted at',
    },
    dosen_add_pjt: {
      filter: 'Filter Students',
      empty_filter: 'No students were found',
      empty_filter_desc: 'Try to change your filters.',
      agkt: 'Cohorts',
      all_agkt: 'All Cohorts',
      jrs: 'Majors',
      all_jrs: 'All Majors',
      khl: 'Skills',
      all_khl: 'All Skills',
      trp_filter: 'Apply Filter',
      nm_pjt: 'Project Name',
      desc_pjt: 'Description (optional)',
      ttl_form: 'Add New Student\'s Projects',
      desc_form: 'Admins can help create and fill portofolio student\'s project.',
      own_pjt: 'Project Owner (owner)',
      pick: 'Pick',
      mhs: 'Students',
      agkt: 'Cohorts',
      jrs: 'Majors',
      act: 'Act',
      see: 'See',
      collab: 'Collaborative Mode',
      desc_collab: 'If turned off, project partners will not be displayed and tasks only from Owner + Leader.',
      add_task: 'Add Task',
      add_task_opt: 'Add Tasks (optional)',
      rsp_task: 'Responsible Person',
      pick_rsp: '-- Pick Responsible Person --',
      nm_task: 'Task Name',
      del: 'Delete',
      add_partner: 'Add Partner (optional)',
      add_partner_choose: '-- Select Project Partner --',
      add_partner_btn: '+ Add Partner',
      date_start: 'Start Date',
      date_end: 'End Date (optional)',
      link_pjt: 'Project Link (optional)',
      link_github: 'GitHub Link (optional)',
      link_vid: 'Video Link (YouTube, optional)',
      cancel: 'Cancel',
      save_pjt: 'Save Project',
      upd_pjt: 'Update Project'
    },
    dosen_sidebar: {
      mhs_bbg: 'Advised Students',
      see_mhs: 'See Students',
      add_mhs: 'Add Student',
      pjt_bbbg: 'Advised Projects',
      see_pjt: 'See Projects',
      add_pjt: 'Add Project',
      stk_bbg: 'Advised Certificates',
      see_stk: 'See Certificates',
      add_stk: 'Add Certificate',
    },
    dosen_stk: {
      ttl_stk: 'Manage All Student Certificates',
      desc_stk: 'Manage All Certificates Owned by Students',
      add_stk: 'Add Certificate',
      del_sel: 'Delete Selected',
      srch: 'Search',
      agkt: 'Cohort',
      all_agkt: 'All Cohorts',
      jrs: 'Major',
      all_jrs: 'All Majors',
      skill: 'Skill',
      all_skill: 'All Skills',
      stat: 'Status',
      all_stat: 'All Statuses',
      trp_filter: 'Apply Filter',
      empty_stk: 'No certificates found.',
      empty_filter: 'Try to change your search features.',
      desc_empty_stk: 'Start adding the first certificates!',
      reset_all: 'Reset All Filters',
      sel_all: 'Select All',
      show: 'Showing',
      from: 'from',
      stk: 'certificates',
      total_pick: 'Total selected:',
      nm_stk: 'Certificate Name:',
      nm_mhs: 'Student Name:',
      see_stk: 'See Certificate',
      desc: 'Description:',
      stat_ajuan: 'Submission Status:',
      stat_active: 'Active Status:',
      added: 'Added at:',
      del: 'Delete',
      acc: 'Accept',
      rej: 'Reject',
    }, 
    dosen_stk_add: {
      ttl_stk: 'Add New Certificate',
      desc_stk: 'Add a certificate obtained by a student to complete their portfolio.',
      filter: 'Filter Students',
      agkt: 'Cohort',
      all_agkt: 'All Cohorts',
      jrs: 'Major',
      all_jrs: 'All Majors',
      skill: 'Skill',
      all_skill: 'All Skills',
      trp_filter: 'Apply Filter',
      pick_mhs: 'Select Student',
      pick: 'Choose',
      nm_mhs: 'Student Name',
      empty_filter: 'No students found',
      empty_filter_desc: 'Try to change your filter searches.',
      nm_stk: 'Certificate Name',
      lembaga: 'Issuing Institution',
      launch_date: 'Launch Date',
      desc_launch: 'Maximum date is today',
      ttl_file: 'Upload Certificate File',
      up_file: 'Upload File',
      or_drag: 'or drag and drop',
      format_file: 'Allowed formats: JPG, JPEG, PNG, GIF. Max size: 5MB',
      uped_file: 'The uploaded file will be stored and can be accessed through a public link.',
      cancel: 'Cancel',
      sv_stk: 'Save Certificate',
    },

    dosen_stk_edit: {
      ttl_form: 'Edit Sertifikat',
      desc_form: 'Update certificate info that you\'ve accumulated.',
      err: 'Theres an error in input:',
      nm_stk: 'Certificate Name',
      lembaga: 'Issuing Constitution',
      tggl_terbit: 'Launch Date',
      maks_tggl: 'Maximum up to this date',
      curr_file: 'Current file:',
      see_file: 'See current file',
      change_file: 'Change File',
      up_file: 'Upload file',
      up_file_opt: 'Upload File (optional)',
      or_drag: 'or drag and drop',
      format_file: 'PNG, JPG, GIF up to 5MB',
      allowed_format: 'Allowed format: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      uped_file: 'Uploaded file will replace the old file. The old file will be deleted automatically.',
      cancel: 'Cancel',
      upd_stk: 'Update Certificate'
    },    

    stk_admin_edit: {
      ttl_edit: 'Edit Certificate',
      back: 'Back',
      nm_stk: 'Certificate name',
      lembaga: 'Issuing Constitution',
      launch_date: 'Launch Date',
      desc_lauch: 'Maximum today\'s date.',
      file_stk: 'Certificate File',
      curr_file: 'Current File:',
      see_file: 'See current file',
      gnt_stk: 'Change File',
      prev_file: 'Current file',
      uped_file: 'Uploaded file will replace the old file. The old file will be automatically deleted.',
      up_file: 'Upload file',
      or_drag: 'or drag and drop',
      format_file: 'PNG, JPG, GIF up to 5MB',
      allowed_format: 'Allowed formats: JPG, JPEG, PNG, GIF. Maximum size: 5MB',
      upd_stk: 'Update Certificate',
      cancel: 'Cancel'
    },
  
    admin: {
      show: 'Showing',
      from: 'from',
      user: 'users',
      admin_dashboard_title: 'Admin Dashboard',
      admin_dashboard_desc: 'System activity summary and key statistics.',
      button_add_user: 'Add User',
      title_jurusan: 'Manage Majors',
      tambah_jurusan: 'Add Major',
      tambah_jurusan_title: 'Add New Major',
      tambah_keahlian_title : 'Add New Skill',
      nama_jurusan: 'Major Name',
      nama_jurusan_label: 'Major Name:',
      lihat_keahlian : 'See Skills',
      nama_jurusan_placeholder: 'Example: Computer Science',
      cari_nama_mahasiswa: 'Search student name...',
      cari_nama_mahasiswa: 'Search student name...',
      aksi: 'Actions',
      tidak_ada_data_jurusan: 'No majors found',
      edit_jurusan: 'Edit Major',
      hapus_jurusan: 'Delete Major',
      hapus_jurusan_prompt: 'Are you sure you want to delete this major?',
      delete_selected: 'Delete Selected',
      no: 'No',
      tambah: 'Add',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      button_user_list: 'User List',
      lihat_prodi : 'See Prodi',
      tambah_prodi : 'Add Prodi',
      lihat_prodi : 'See Prodi',
      tambah_prodi : 'Add Prodi',
      button_all_projects: 'All Projects',
      button_certificates: 'Certificates',
      total_users_title: 'Total Users',
      total_users_desc: 'Registered users count',
      total_students_title: 'Total Students',
      total_students_desc: 'Active students count',
      total_admin_title: 'Total Admins',
      total_admin_desc: 'Registered admin accounts',
      total_lecturers_title: 'Total Lecturers',
      total_lecturers_desc: 'Registered lecturer accounts',
      highlight_title: 'Highlights',
      students_label: 'students',
      projects_label: 'projects',
      learning_corners_label: 'learning corners',
      certificates_label: 'certificates',
      registered_label: 'registered',
      total_projects_title: 'Total Projects',
      total_learning_corners_title: 'Total Learning Corners',
      total_certificates_title: 'Total Certificates',
      latest_activity_title: 'Latest Activity (Projects, Certificates, Learning Corners)',
      latest_activity_desc: 'See the latest platform activity',
      see_all: 'See All',
      project_no_title: 'Untitled project',
      posted_by: 'Posted by',
      student_label: 'student',
      no_recent_activity: 'No recent activity yet',
      show_more: 'Show more',
      pending_students_title: 'Pending Students',
      pending_students_desc: 'Students awaiting account verification',
      pending_students_empty: 'No students are currently pending approval.',
      rejected_students_title: 'Rejected Students',
      rejected_students_desc: 'Students whose requests have been rejected',
      rejected_students_empty: 'No rejected students.',
      //user form
      tambah_user_form: 'Add New User',
      pilih_role: 'Select the role for the new user',
      role_admin: 'Admin',
      desc_admin: 'Full access for system management',
      form_admin: 'Simple Form',
      role_mhs: 'student',
      desc_mhs: 'Access to follow academic activity',
      form_mhs: 'Detailed form',
      role_dosen: 'Lecturer',
      desc_dosen: 'Access to manage academic activity',
      form_dosen: 'Detailed Form',
      info: 'Basic Information',
      nm_lgkp: 'Full Name',
      usrnm: 'Username',
      usrnm_error: 'Only letters, Numbers, and underscores (_)',
      email: 'Email',
      pw: 'Password',
      pw_confirm: 'Confirm Password',
      pfp: 'Photo Profile',
      info_lebih: 'More Information',
      jurusan: 'Programs',
      opt_jurusan: 'Choose a Program',
      jurusan: 'Programs',
      opt_jurusan: 'Choose a Program',
      keahlian: 'Skills',
      opt_keahlian: 'Choose a Skill',
      angkatan: 'Cohorts',
      opt_angkatan: 'Choose a Cohort',
      cncl: 'Cancel',
      tambah: 'Add User',
      //
      semua_user: 'See All Users',
      tambah_user: 'Add User',
      lihat_proyek: 'See Projects',
      tambah_proyek: 'Add Project',
      lihat_angkatan: 'See Cohorts',
      tambah_angkatan: 'Add Cohort',
      lihat_sertifikat: 'See Certificates',
      tambah_sertifikat: 'Add Certificates',
      tambah_user: 'Add New User',
      //Halaman lihat semua user
      kll_pengguna: 'Manage Users',
      desc_kll_pengguna: 'Manage all users registered.',
      del_user: 'Delete Selected',
      add_user: 'Add User',
      srch_usr: 'Search',
      search_placeholder: 'Search by name, username, or email..',
      role_usr: 'Role',
      role_usr1: 'All Roles',
      stat_acc: 'Account Status',
      stat_pengajuan: 'Submission Status',
      stat_diterima: 'Accepted',
      stat_ditolak: 'Rejected',
      stat_aktif: 'Active',
      stat_non_aktif: 'Non Active',
      all_stat: 'All Statuses',
      reset_filter: 'Reset Filter',
      trp_filter: 'Apply Filter',
      plh_semua: 'Select All',
      total_dipilih: 'Total selected:',
      tbl_foto: 'Photo',
      tbl_nm: 'NAME / USERNAME',
      tbl_email: 'EMAIL',
      tbl_role: 'ROLE',
      tbl_stat: 'STATUS',
      tbl_jrs: 'MAJOR',
      tbl_agkt: 'COHORT',
      tbl_act: 'ACTION',
      detail_prodi_title: 'Department Details',
      nama_prodi_label: 'Department Name',
      total_mahasiswa: 'Total Students',
      statistik_mahasiswa: 'Student Statistics',
      grafik_status_mahasiswa: 'Student Status Chart',
      daftar_mahasiswa: 'Student List',
      tidak_ada_mahasiswa_prodi: 'No students in this department.',
      detail_prodi_title: 'Department Details',
      nama_prodi_label: 'Department Name',
      total_mahasiswa: 'Total Students',
      statistik_mahasiswa: 'Student Statistics',
      grafik_status_mahasiswa: 'Student Status Chart',
      daftar_mahasiswa: 'Student List',
      tidak_ada_mahasiswa_prodi: 'No students in this department.',
      //Halmaan tambah user
      info_adduser: 'Basic Information',
      nm_lgkp: 'Full Name',
      usr_req: 'Only letters, numbers, and underscores (_)',
      pw_adduser: 'Password',
      pw_confirm_adduser: 'Confirm Password',
      add_addusr: 'Add User',
      cancel_addusr: 'Cancel',
      more_info_addusr: 'More Information',
      jrs_addusr: 'Major',
      chs_jrs_addusr: 'Choose Major',
      exp_addusr: 'Skill',
      chs_exp_addusr: 'Choose Skill',
      agkt_addusr: 'Cohort',
      chs_agkt_addusr: 'Choose Cohort',
      //Edit user (menggunakan form yang sama dengan halaman tambah user, hanya data tambahan yang belum)
      back: 'Back',
      pw_new: 'New Password (empty if not changing)',
      pw_new_confirm: 'Confirm New Password',
      pfp_new: 'Profile Photo',
      pfp_frmt: 'Format: JPEG, PNG, JPG. Max: 2MB',
      save_new: 'Save Changes',
      //Halaman Manajemen Project
      delete_select: 'Delete Selected',
      select_all: 'Select All',
      selected: 'Selected:',
      empty_project: 'No projects to display.',
      desc_empty_project: 'Please add a new project to get started.',
      edit_project: 'Edit',
      delete_project: 'Delete',
      //Halaman Create Project
      filter_mhs: 'Filter Students',
      all_cohorts: 'All Cohorts',
      all_jrs: 'All Majors',
      all_skill: 'All Skills',
      nm_project: 'Project Name',
      desc_project: 'Description (optional)',
      leader_project: 'Select Student (Project Leader)',
      tbl_pjt_1: 'SELECT',
      tbl_pjt_2: 'STUDENT',
      tbl_pjt_3: 'COHORT',
      tbl_pjt_4: 'MAJOR',
      tbl_pjt_5: 'SKILL',
      tbl_pjt_6: 'ACTION',
      act_tbl: 'View',
      empty_filter: 'No students found',
      empty_filter_desc: 'Try changing your search filters',
      partner_project: 'Add Partners (optional)',
      partner_choice: '-- Select Project Partners --',
      add_partner: 'Add Partners',
      date_start: 'Start Date',
      date_end: 'End Date (optional)',
      date_end_must: 'End Date',
      //Ha;laman edit proyek
      title_edit: 'Edit Project',
      desc_edit: 'Edit project information or replace files if necessary. Make sure to save changes when finished.',
      //Halaman tambah angkatan
      title_agkt: 'Cohort List',
      add_agkt: 'Add Cohort',
      no_agkt: 'NO',
      nm_agkt: 'COHORT NAME',
      thn_agkt: 'YEAR IN',
      exit_agkt: 'YEAR OUT',
      total_mhs: 'TOTAL STUDENTS',
      aksi_agkt: 'ACTION',
      //Halaman detail angkatan
      detail_agkt: 'Cohort Detail',
      nm_agkt_kcl: 'Cohort Name',
      thn_agkt_kcl: 'Year In',
      exit_agkt_kcl: 'Year Out',
      mhs_stats: 'Student Statistics',
      total_mhs_agkt: 'Total Students',
      list_mhs: 'Student List',
      no_agkt_mhs: 'NO',
      nm_mhs_agkt: 'NAME',
      jrs_agkt: 'MAJOR',
      stat_agkt: 'STATUS',
      ///halaman tambah angkatan
      add_agkt: 'Add New Cohort',
      desc_agkt_exit: 'Leave empty if not graduated yet',
      addadd_agkt: 'Add Cohort',
      //Halaman kelola sertifikat
      title_srtfkt: 'Manage All Certificates',
      desc_srtfkt: 'Manage All Certificates Owned by Students',
      empty_srtfkt: 'No certificates found.',
      empty_desc_srtfkt: 'Start adding the first certificate!',
      add_srtfkt: 'Add Certificate',
      stat_filter: 'Status',
      stat_filter_all: 'All Statuses',
      tmplkn: 'Showing',
      dr: 'of',
      srtfkt: 'certificates',
      nm_srtfkt: 'Certificate Name:',
      nm_mhs_srtfkt: 'Student Name:',
      stat_active: 'Active Status',
      title_srtfkt_create: 'Add New Certificate',
      desc_srtfkt_create: 'Add certificates you have earned to complete your portfolio.',
      pilih_mhs: 'Select Student',
      nm_mhs: 'Student Name',
      see_profile: 'See Profile →',
      nm_srtfkt_create: 'Certificate Name',
      lembaga_penerbit: 'Issuing Institution',
      tggl_terbit: 'Date of Issue',
      max_tggl: 'Maximum date is today',
      upload_srtfkt: 'Upload Certificate File',
      up_file: 'Upload File',
      or_drag: 'or drag and drop',
      format_srtfkt: 'Allowed formats: PNG, JPG, GIF, Max size: 5MB',
      save_srtfkt: 'Save Certificate',
      edit_srtfkt : 'Edit Certificate',
      hapus_srtfkt: 'Delete Certificate',
      // Keahlian management
      title_keahlian: 'Skills List',
      nama_keahlian: 'Skill Name',
      nama_keahlian_label: 'Skill Name',
      nama_keahlian_placeholder: 'Example: Web Development',
      tambah_keahlian: 'Add Skill',
      detail_keahlian_title: 'Skill Details',
      tambah_jurusan_title: 'Add New Skill',
      nama_jurusan_label: 'Skill Name',

    },

    dashboard: {
      postingan_kosong: 'There are no posts to be displayed currently',
      total_mahasiswa: 'Total Students',
      semua_learning_corner: 'All Learning Corners',
      total_project: 'Total Projects',
      total_sertifikat: 'Total Certificates',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',
      ttl_pjt: 'Projects',
      ttl_stk: 'Certificates',
      ttl_lrn: 'Learning Corner',
      empty_lrn: 'There is no learning corner yet.',
      empty_pjt: 'There is no project posts yet.',
      empty_stk: 'There is no Certificate posts yet.'
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Projects Done',
      total_sertifikat: 'Total Certificates Earned',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',

    },
    portofolio_user: {
      portfolio: 'Portfolio',
      prodi: 'Study Program :',
      agkt: 'Cohorts',
      khl: 'Skills',
      Utama: 'Main: ',
      pjt: 'Projects',
      done: 'Finished',
      ongoing: 'On Progress',
      soon: 'Coming Soon',
      show_done: 'Showing finished projects',
      show_ongoing: 'Showing on progress projects',
      show_soon: 'Showing coming soon projects',
      show_all: 'Showing all projects',
      pjt_noneownlead: 'No owner/Leader',
      pjt_nolead: 'No leader',
      pjt_own: 'Project Owner',
      pjt_ownnone: 'No owner',
      pjt_noteam: 'No team members',
      pjt_desc: 'Description',
      pjt_vidprev: 'Preview Video',

      team: 'Team Members',
      start: 'Start',
      end: 'Finish',
      stk: 'Certificates',
      lrn: 'Learning Corner',
      note: 'Notes',
      empty_content: 'There is no content to be shown',
      lrn_origin: 'From project: ',
      empty_lrn: 'There is no learning corner yet'
    },
    project: {
      project_saya: 'My Projects',
      deskripsi: 'Manage your projects, both those you lead and those you participate in as a team member.',
      tambah_project: 'Add New Project',
      edit_project: 'Edit Project',
      hapus_project: 'Delete Project',
      pemilik: 'Owner',
      leader: 'Leader',
      anggota: 'Members',
      no_project: 'No projects associated with your account.',
      dibuat_oleh: 'Created by',
      mulai: 'Start',
      selesai: 'Finish',
      lihat_project: 'View Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      tambah_project: 'Add New Project',
      desc_create: 'Add projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      tambah_pemimpin: 'Add Leader (optional)',
      tambah_rekan: 'Add Members (optional)',
      tambah_rekan_btn: '+ Add Members',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date (optional)',
      link_project_opsional: 'Project Link (optional)',
      link_github_opsional: 'GitHub Link (optional)',
      link_video_opsional: 'Video Link (YouTube, optional)',
      simpan_project: 'Save Project',
      // Detail Angkatan
      nm_agkt: 'Cohort Name',
      thn_msk: 'Entry Year',
      thn_klr: 'Exit Year',
      blm_ttk: 'Not determined yet',
      stat_mhs: 'Student Statistics',
      ttl_mhs: 'Total Students',
      aktf: 'Active',
      tdk_aktf: 'Inactive',
      grfk_stat_mhs: 'Student Status Graph',
      dft_mhs: 'Student List',
      flt_pencarian: 'Filter & Search',
      cri_nm_mhs: 'Search student name...',
      flt_jrs: 'Filter Major',
      smw_jrs: 'All Majors',
      flt_stat: 'Filter Status',
      smw_stat: 'All Status',
      rst_flt: 'Reset Filter',
      trp_flt: 'Apply Filter',
      tmpilkan: 'Showing',
      no: 'No',
      nm_mhs: 'Student Name',
      jrs: 'Major',
      eml: 'Email',
      stat: 'Status',
      aksi: 'Action',
      tdk_ada_mhs_ttm: 'No students found',
      cba_ubh_flt: 'Try changing your search filter or search with other keywords',
      tdk_ada_mhs_angkt: 'No students in this cohort.',
      lht: 'View',
      // Detail Angkatan
      nm_agkt: 'Cohort Name',
      thn_msk: 'Entry Year',
      thn_klr: 'Exit Year',
      blm_ttk: 'Not determined yet',
      stat_mhs: 'Student Statistics',
      ttl_mhs: 'Total Students',
      aktf: 'Active',
      tdk_aktf: 'Inactive',
      grfk_stat_mhs: 'Student Status Graph',
      dft_mhs: 'Student List',
      flt_pencarian: 'Filter & Search',
      cri_nm_mhs: 'Search student name...',
      flt_jrs: 'Filter Major',
      smw_jrs: 'All Majors',
      flt_stat: 'Filter Status',
      smw_stat: 'All Status',
      rst_flt: 'Reset Filter',
      trp_flt: 'Apply Filter',
      tmpilkan: 'Showing',
      no: 'No',
      nm_mhs: 'Student Name',
      jrs: 'Major',
      eml: 'Email',
      stat: 'Status',
      aksi: 'Action',
      tdk_ada_mhs_ttm: 'No students found',
      cba_ubh_flt: 'Try changing your search filter or search with other keywords',
      tdk_ada_mhs_angkt: 'No students in this cohort.',
      lht: 'View',
    },
    project_edit: {
      title: 'Edit Project',
      desc: 'Edit project details or replace files if necessary. Make sure to save changes when you are done.',
      filter_mhs: 'Filter Students',
      angkatan: 'Cohort',
      jurusan: 'Program',
      jurusan: 'Program',
      keahlian: 'Skill',
      semua_angkatan: 'All Cohorts',
      semua_jurusan: 'All Programs',
      semua_jurusan: 'All Programs',
      semua_keahlian: 'All Skills',
      reset_filter: 'Reset Filter',
      apply_filter: 'Apply Filter',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      leader_project: 'Select Student (Project Leader)',
      selected_leader_prefix: 'Leader:',
      leader_search_placeholder: 'Search project leader name...',
      pilih_col: 'Select',
      mahasiswa_col: 'Student',
      angkatan_col: 'Cohort',
      jurusan_col: 'Program',
      jurusan_col: 'Program',
      keahlian_col: 'Skill',
      aksi_col: 'Action',
      lihat: 'View',
      no_students_found: 'No students found',
      change_filter_hint: 'Try changing your search filters',
      add_member: 'Add Partner (optional)',
      add_member_btn: '+ Add Partner',
      member_search_placeholder: 'Search partner name...',
      no_students_available: 'No students available',
      name_unknown: 'Unknown Name',
      select_member_option: '-- Select Project Partner --',
      already_selected_suffix: ' (Already selected)',
      leader_suffix: ' (Leader)',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date (optional)',
      link_project_opsional: 'Project Link (optional)',
      link_github_opsional: 'GitHub Link (optional)',
      link_video_opsional: 'Video Link (YouTube, optional)',
      cancel: 'Cancel',
      update_project: 'Update Project',
    },
    project_detail: {
      detail_project: 'Project Detail',
      desc_detail: 'View details of projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      students_involved: 'Students Involved',
      tambah_pemimpin: 'Team Leader',
      no_leader: 'No leader',
      tambah_rekan: 'Team Members',
      no_member: 'No members',
      time_period: 'Time Period',
      links: 'Links',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Delete Selected',
      add_new_note: '+ Add New Note',
      no_learning_corner: 'No Learning Corner notes in this project.',
      select_to_delete: 'Select to delete',
      edit: 'Edit',
      delete: 'Delete',
      status_incoming: 'Upcoming',
      status_present: 'Ongoing',
      status_past: 'Finished',
      progress_done: 'Done',
    },
    search: {
      search: 'Search',
      search_placeholder: 'Search projects, certificates, or learning corners...',
      placeholder_student: 'Search Students...',
      placeholder_portfolio: 'Search Portfolio...',
      placeholder_certificate: 'Search Certificate...',
      filter_jurusan: 'All Programs',
      filter_jurusan: 'All Programs',
      filter_keahlian: 'All Skills',
      filter_angkatan: 'All Cohorts',
    },
    result_search: {
      hasil_pencarian: 'Search Results',
      filter_aktif: 'Active filter:',
      clr_filter: 'Clear all filters',
      mhs: 'Students',
      khl: 'Skills',
      khl: 'Skills',
      tampil: 'See all',
      sembunyi: 'Hide',
      prtfl_lengkap: 'See complete portofolio →',
      sertifikat: 'Certificates',
      none: 'There are no results',
      none_desc: 'Try to search for other keyword, Majors/Skills/Cohorts or to delete the filters above.',
      empty_link: 'There are no link project',
      oleh: 'By',
      see_project: 'See Project →'
    },
    sidebar: {
      dashboard: 'Home',
      dashboard_nonuser: 'Home',
      my_dashboard: 'My Dashboard',
      manajemen_users: 'User Management',
      semua_user: 'See All Users',
      tambah_user: 'Add User',
      lihat_proyek: 'See Projects',
      tambah_proyek: 'Add Project',
      lihat_angkatan: 'See Cohorts',
      lihat_sertifikat: 'See Certificates',
      manajemen_projects: 'Project Management',
      manajemen_sertifikat: 'Certificate Management',
      manajemen_angkatan: 'Angkatan Management',
      manajemen_prodi: 'Prodi Management',
      lihat_prodi: 'See Prodi',
      tambah_prodi: 'Add Prodi',
      manajemen_keahlian: 'Skills Management',
      lihat_keahlian: 'See Skills',
      tambah_keahlian: 'Add Skills',
      dashboard_dosen: 'Lecturer Dashboard',
      mahasiswa_bimbingan: 'Supervised Students',
      projects_bimbingan: 'Supervised Projects',
      sertifikat_bimbingan: 'Supervised Certificates',
      project_mahasiswa: 'Student Projects',
      project_mahasiswa_saya: 'My Projects',
      project_mahasiswa_saya_tambah: 'Add New Project',
      sertifikat_mahasiswa: 'Student Certificates',
      sertifikat_mahasiswa_saya: 'My Certificates',
      sertifikat_mahasiswa_saya_tambah: 'Add New Certificate',
      corner_mahasiswa: 'Student Corner',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Language',
      logout: 'Logout',
      login: 'Login',
      login_prompt: 'Are you a student? Login now!',
      register: 'Register',
    },
    footer: {
      footer_rights: '© 2026 Portofolio Mahasiswa. All rights reserved.',
    },
    project_user: {
      project_user_title: 'Project',
      project_user_desc: 'List of projects made by our students.',
      nama_project: 'Project Name',
      tanpa_nama_project: "Untitled Project",
      tidak_diketahui: "Unknown",
      selesai: "Finished",
      sedang_berjalan: "Ongoing",
      akan_datang: "Upcoming",
      sekarang: "Now",
      diposting: 'Posted',
      no_thumbnail_text: 'No thumbnail available',
      no_thumbnail_description: 'add a video link correctly',
    },
    sertifikat: {
      sertifikat_title: 'My Certificates',
      sertifikat_desc: 'Manage all the certificates you have here.',
      sertifikat_create_button: 'Add New Certificate',
      sertifikat_no_data: 'No certificates yet.',
      sertifikat_no_data_description: 'Start adding your first certificate!',
      sertifikat_link: 'View Certificate',
      sertifikat_dibuat: 'Added',
      sertifikat_diupdate: 'Updated',
      edit_button: 'Edit',
      delete_button: 'Delete',
    },
    sertifikat_user: {
      sertifikat_title: 'My Certificates',
      sertifikat_desc: 'Manage all the certificates you have here.',
      sertifikat_mahasiswa_title: 'Student Certificates',
      sertifikat_mahasiswa_desc: 'View student certificates',
      sertifikat_create_button: 'Add New Certificate',
      sertifikat_no_data: 'No certificates yet.',
      sertifikat_no_data_description: 'Start adding your first certificate!',
      sertifikat_link: 'View Certificate',
      sertifikat_dibuat: 'Added',
      sertifikat_diupdate: 'Updated',
    },
    sertifikat_create: {
      sertifikat_create_title: 'Add New Certificate',
      sertifikat_create_desc: 'Add the certificates you have earned to complete your portfolio.',
      nama_sertifikat: 'Certificate Name',
      error_global_title: 'There are errors with the input:',
      tanggal_terbit: 'Issue Date',
      lembaga_penerbit: 'Issuing Institution',
      upload_file_sertifikat: 'Upload Certificate File',
      upload_file: 'Upload File',
      or_drag_drop: 'or drag and drop',
      max_date: 'Maximum date is today',
      upload_file_desc: 'Allowed formats: JPG, JPEG, PNG, GIF. Maximum size: 5MB',
      upload_file_tips: 'Uploaded files will be stored and accessible via a public link.',
      cancel: 'Cancel',
      save: 'Save Certificate'

    },
    sertifikat_edit: {
      sertifikat_edit_title: 'Edit Certificate',
      sertifikat_edit_desc: 'Update the information of the certificate you have.',
      error_global_title: 'There are errors with the input:',
      nama_sertifikat: 'Certificate Name',
      lembaga_penerbit: 'Issuing Institution',
      tanggal_terbit: 'Issue Date',
      max_date: 'Maximum date is today',
      upload_file_sertifikat: 'Upload Certificate File',
      replace_file: 'Replace File',
      upload_file: 'Upload File',
      or_drag_drop: 'or drag and drop',
      current_file: 'Current File',
      view_current_file: 'View Current File',
      upload_file_desc: 'Allowed formats: JPG, JPEG, PNG, GIF. Maximum size: 5MB',
      upload_file_tips: 'Uploaded files will be stored and accessible via a public link.',
      new_file_preview: 'New File Preview:',
      current_file_preview: 'Current File:',
      additional_info: 'The uploaded file will replace the old file. The old file will be automatically deleted.',
      cancel: 'Cancel',
      update_sertifikat: 'Update Certificate',
    },
    kelola_user: {
      kelola_user_title: 'Manage Users',
      kelola_user_desc: 'Add, edit, or delete users in the system.',
      status_diterima: 'Accepted',
      status_ditolak: 'Rejected',
      status_sedang_di_ajukan: 'Pending',
      tambah_user: 'Add User',
      edit_user: 'Edit User',
      hapus_user: 'Delete User',
      sertifikat_title: 'Certificates',
      aksi: 'Actions',
    },
    kelola_project: {
      kelola_project_title: 'Manage Projects',
      kelola_project_desc: 'Add, edit, or delete projects in the system.',
      tambah_project: 'Add Project',
      edit_project: 'Edit Project',
      hapus_project: 'Delete Project',
      nama_project: 'Project Name',
      deskripsi: 'Description',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date',
      link_project: 'Project Link',
      link_github: 'GitHub Link',
      link_video: 'Video Link',
      diposting: 'Posted',
    },
    kelola_create_project: {
      kelola_create_project_title: 'Add Project',
      kelola_create_project_desc: 'Add projects that students have created.',
      nama_project: 'Project Name',

    },

  }
};


const DEFAULT_LANG = 'id';
let currentLang = localStorage.getItem('lang') || DEFAULT_LANG;

let translateElements = [];

function cacheTranslateElements() {
  translateElements = Array.from(document.querySelectorAll('[data-translate]'));
}

function applyTranslations() {
  const langData = translations[currentLang] || translations[DEFAULT_LANG];

  const translateKey = (page, key) => langData?.[page]?.[key] || translations[DEFAULT_LANG]?.[page]?.[key] || key;

  translateElements.forEach(el => {
    const page = el.dataset.translatePage || 'sidebar';
    const key = el.dataset.translate;

    if (page && key) {
      const text = translateKey(page, key);
      if (text !== el.textContent) {
        el.textContent = text;
      }
    }

    const placeholderKey = el.dataset.translatePlaceholder;
    if (placeholderKey) {
      const placeholderText = translateKey(el.dataset.translatePage || 'sidebar', placeholderKey);
      if (placeholderText) {
        el.setAttribute('placeholder', placeholderText);
      }
    }
  });

  const select = document.getElementById('languageSelect');
  if (select) select.value = currentLang;
}

window.changeLanguage = function () {
  const select = document.getElementById('languageSelect');
  if (!select) return;

  const newLang = select.value;
  if (newLang === currentLang) return;

  currentLang = newLang;
  localStorage.setItem('lang', newLang);
  document.documentElement.lang = newLang === 'id' ? 'id-ID' : 'en-US';

  applyTranslations();
};

document.addEventListener('DOMContentLoaded', () => {
  const select = document.getElementById('languageSelect');
  if (select) {
    select.value = currentLang;
  }

  cacheTranslateElements();
  applyTranslations();
});
window.refreshTranslations = function () {
  cacheTranslateElements();
  applyTranslations();
};