export const translations = {
  id: {
    dashboard: {
      total_mahasiswa: 'Total Seluruh Mahasiswa',
      semua_learning_corner: 'Semua Learning Corner',
      total_project: 'Total Semua Project',
      total_sertifikat: 'Total Semua Sertifikat',
      perihal_terbaru: 'Perihal Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'Sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Project Dikerjakan',
      total_sertifikat: 'Total Sertifikat Didapat',
      perihal_terbaru: 'Perihal Terbaru',
      lihat_semua: 'Lihat Semua →',
      tampilkan_lagi: 'tampilkan lagi',
      sembunyikan: 'sembunyikan',
      project_terkait: 'Project Terkait:',
      link_project: 'Link Project',
      project_detail: 'Lihat Detail Project',
      diposting: 'Diposting',
      oleh: 'oleh',
      untuk_project: 'untuk project',
      terakhir_diperbarui: 'Data terakhir diperbarui:',
    },
    project: {
      project_saya: 'Project Saya',
      deskripsi: 'Kelola project milikmu, yang kamu pimpin, dan yang kamu ikuti sebagai anggota tim.',
      tambah_project: 'Tambah Project Baru',
      edit_project: 'Edit Project',
      hapus_project: 'Hapus Project',
      pemilik: 'Pemilik',
      leader: 'Leader',
      anggota: 'Anggota',
      no_project: 'Belum ada project yang terkait dengan akunmu.',
      dibuat_oleh: 'Dibuat oleh',
      mulai: 'Mulai',
      selesai: 'Selesai',
      lihat_project: 'Lihat Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      tambah_project: 'Tambah Project Baru',
      edit_project: 'Edit Project',
      edit_project: 'Edit Project',
      desc_create: 'Tambah project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
    },
    project_detail: {
      detail_project: 'Detail Project',
      desc_detail: 'Lihat detail project yang pernah kamu buat.',
      nama_project: 'Nama Project',
      deskripsi_opsional: 'Deskripsi (opsional)',
      students_involved: 'Siswa Terlibat',
      tambah_pemimpin: 'Pemimpin Tim',
      no_leader: 'Tidak ada leader',
      tambah_rekan: 'Rekan Rekan Kerja',
      no_member: 'Tidak ada rekan',
      time_period: 'Periode Waktu',
      links: 'Link',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Hapus Terpilih',
      add_new_note: '+ Tambah Catatan Baru',
      no_learning_corner: 'Belum ada catatan Learning Corner di project ini.',
      select_to_delete: 'Pilih untuk dihapus',
      edit: 'Edit',
      delete: 'Hapus',
      status_incoming: 'Akan Datang',
      status_present: 'Sedang Berjalan',
      status_past: 'Selesai',
      progress_done: 'Selesai',
    },
    portofolio_user: {
      portfolio: 'Portfolio',
    },
    search: {
      search: 'Cari',
      search_placeholder: 'Cari project, sertifikat, atau learning corner...',
      filter_jurusan: 'Semua Jurusan',
      filter_keahlian: 'Semua Keahlian',
      filter_angkatan: 'Semua Angkatan',
    },
    result_search: {
      hasil_pencarian: 'Hasil Pencarian',
      filter_aktif: 'Filter aktif:',
    },
    sidebar: {
      dashboard: 'Dashboard',
      my_dashboard: 'My Dashboard',
      manajemen_users: 'Manajemen User',    
      manajemen_projects: 'Manajemen Project',
      manajemen_sertifikat: 'Manajemen Sertifikat',
      manajemen_angkatan : 'Manajemen Angkatan',
      dashboard_dosen: 'Dashboard Dosen',
      mahasiswa_bimbingan: 'Mahasiswa Bimbingan',
      projects_bimbingan: 'Projects Bimbingan',
      sertifikat_bimbingan: 'Sertifikat Bimbingan',
      project_mahasiswa: 'Project Mahasiswa',
      project_mahasiswa_saya: 'Project Saya',
      project_mahasiswa_saya_tambah: 'Tambah Project Baru',
      sertifikat_mahasiswa: 'Sertifikat Mahasiswa',
      sertifikat_mahasiswa_saya: 'Sertifikat Saya',
      sertifikat_mahasiswa_saya_tambah: 'Tambah Sertifikat',
      corner_mahasiswa: 'Corner Mahasiswa',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Bahasa',
      logout: 'Logout',
      login: 'Masuk',
      login_prompt: 'Kamu Mahasiswa? Login Sekarang!',
      register: 'Register',
    },
     footer: {
      footer_rights: '© Portofolio Mahasiswa 2026. Semua hak dilindungi undang-undang.',
    },
    project_user: {
      project_user_title: 'Project ',
      project_user_desc: 'Daftar project yang kamu ikuti sebagai anggota.',
      nama_project: 'Nama Project',
      tanpa_nama_project:      "Tanpa Nama Project",
      tidak_diketahui:         "Tidak diketahui",
      selesai:                 "Selesai",
      sedang_berjalan:         "Sedang Berjalan",
      akan_datang:             "Akan Datang",
      sekarang:                "Sekarang",
      deskripsi_opsional: 'Deskripsi (opsional)',
      tambah_pemimpin: 'Tambah Pemimpin (opsional)',
      tambah_rekan: 'Tambah Anggota (opsional)',
      tambah_rekan_btn: '+ Tambah Anggota',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai (opsional)',
      link_project_opsional: 'Link Project (opsional)',
      link_github_opsional: 'Link GitHub (opsional)',
      link_video_opsional: 'Link Video (YouTube, opsional)',
      simpan_project: 'Simpan Project',
      diposting: 'Diposting',
      no_thumbnail_text: 'Tidak ada thumbnail tersedia',
      no_thumbnail_description: 'Tambahkan link video dengan benar',
    },
    sertifikat: { 
      sertifikat_title: 'Sertifikat Saya',
      sertifikat_desc: 'Kelola semua sertifikat yang kamu miliki di sini.',
      sertifikat_create_button: 'Tambah Sertifikat Baru',
      sertifikat_no_data: 'Belum ada sertifikat.',
      sertifikat_no_data_description: 'Mulai tambahkan sertifikat pertama kamu!',
      sertifikat_link: 'Lihat Sertifikat',
      sertifikat_dibuat: 'Ditambahkan',
      sertifikat_diupdate: 'Diupdate',
      edit_button: 'Edit',
      delete_button: 'Hapus',
    },

    sertifikat_user: { 
      sertifikat_title: 'Sertifikat Saya',
      sertifikat_desc: 'Kelola semua sertifikat yang kamu miliki di sini.',
      sertifikat_create_button: 'Tambah Sertifikat Baru',
      sertifikat_no_data: 'Belum ada sertifikat.',
      sertifikat_no_data_description: 'Mulai tambahkan sertifikat pertama kamu!',
      sertifikat_link: 'Lihat Sertifikat',
      sertifikat_dibuat: 'Ditambahkan',
      sertifikat_diupdate: 'Diupdate',
    },

    sertifikat_create: {
      sertifikat_create_title: 'Tambah Sertifikat Baru',
      sertifikat_create_desc: 'Tambahkan sertifikat yang kamu peroleh untuk melengkapi portofoliomu.',
      nama_sertifikat: 'Nama Sertifikat',
      error_global_title: 'Terdapat kesalahan pada input:',
      tanggal_terbit: 'Tanggal Terbit',
      lembaga_penerbit: 'Lembaga Penerbit',
      upload_file_sertifikat: 'Upload File Sertifikat',
      max_date: 'Maksimal tanggal hari ini',
      upload_file: 'Upload File',
      or_drag_drop: 'atau drag and drop',
      upload_file_desc: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      upload_file_tips: 'File yang diupload akan tersimpan dan dapat diakses melalui link publik.',
      cancel: 'Batal',
      save: 'Simpan Sertifikat'
    
    },

    sertifikat_edit: { 
      sertifikat_edit_title: 'Edit Sertifikat',
      sertifikat_edit_desc: 'Perbarui informasi sertifikat yang kamu miliki.',
      error_global_title: 'Terdapat kesalahan pada input:',
      nama_sertifikat: 'Nama Sertifikat',
      lembaga_penerbit: 'Lembaga Penerbit',
      tanggal_terbit: 'Tanggal Terbit',
      max_date: 'Maksimal tanggal hari ini',
      upload_file_sertifikat: 'Upload File Sertifikat',
      replace_file: 'Ganti File',
      upload_file: 'Upload File',
      or_drag_drop: 'atau drag and drop',
      current_file: 'File Saat Ini',
      view_current_file: 'Lihat File Saat Ini',
      upload_file_desc: 'Format yang diperbolehkan: JPG, JPEG, PNG, GIF. Maksimal ukuran: 5MB',
      upload_file_tips: 'File yang diupload akan tersimpan dan dapat diakses melalui link publik.',
      new_file_preview: 'Preview File Baru:',
      current_file_preview: 'File Saat Ini:',
      additional_info: 'File yang diupload akan menggantikan file lama. File lama akan otomatis dihapus.',
      cancel: 'Batal',
      update_sertifikat: 'Update Sertifikat', 
    },
    kelola_user: {
      kelola_user_title: 'Kelola Users',
      kelola_user_desc: 'Tambah, edit, atau hapus user di sistem.',
      status_diterima: 'Diterima',
      status_ditolak: 'Ditolak',
      status_sedang_di_ajukan: 'Sedang Di Ajukan',
      tambah_user: 'Tambah User',
      edit_user: 'Edit User',
      hapus_user: 'Hapus User',
      sertifikat_title: 'Sertifikat',
      aksi: 'Aksi',
    },
    kelola_project: {
      kelola_project_title: 'Kelola Projects',
      kelola_project_desc: 'Tambah, edit, atau hapus project di sistem.',
      tambah_project: 'Tambah Project',
      edit_project: 'Edit Project',
      hapus_project: 'Hapus Project',
      nama_project: 'Nama Project',
      deskripsi: 'Deskripsi',
      tanggal_mulai: 'Tanggal Mulai',
      tanggal_selesai: 'Tanggal Selesai',
      link_project: 'Link Project',
      link_github: 'Link GitHub',
      link_video: 'Link Video',
      diposting: 'Diposting',
    },
    kelola_create_project: {
      kelola_create_project_title: 'Tambah Project',
      kelola_create_project_desc: 'Tambah project yang pernah dibuat oleh mahasiswa.',
      nama_project: 'Nama Project',

    },

  }, 
  en: {
    dashboard: {
      total_mahasiswa: 'Total Students',
      semua_learning_corner: 'All Learning Corners',
      total_project: 'Total Projects',
      total_sertifikat: 'Total Certificates',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',
    },
    dashboard_me: {
      learning_corner: 'Learning Corner',
      total_project: 'Total Projects Done',
      total_sertifikat: 'Total Certificates Earned',
      perihal_terbaru: 'Latest Topics',
      lihat_semua: 'See All →',
      tampilkan_lagi: 'more',
      sembunyikan: 'hide',
      project_terkait: 'Related Projects:',
      link_project: 'Project Link',
      project_detail: 'View Project Details',
      diposting: 'Posted',
      oleh: 'by',
      untuk_project: 'for project',
      terakhir_diperbarui: 'Last updated:',
      
    },
    portofolio_user: {
      portfolio: 'Portfolio',
    },
    project: {
      project_saya: 'My Projects',
      deskripsi: 'Manage your projects, both those you lead and those you participate in as a team member.',
      tambah_project: 'Add New Project',
      edit_project: 'Edit Project',
      hapus_project: 'Delete Project',
      pemilik: 'Owner',
      leader: 'Leader',
      anggota: 'Members',
      no_project: 'No projects associated with your account.',
      dibuat_oleh: 'Created by',
      mulai: 'Start',
      selesai: 'Finish',
      lihat_project: 'View Project',
      github: 'GitHub',
      video: 'Video',
    },
    project_create: {
      tambah_project: 'Add New Project',
      desc_create: 'Add projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      tambah_pemimpin: 'Add Leader (optional)',
      tambah_rekan: 'Add Members (optional)',
      tambah_rekan_btn: '+ Add Members',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date (optional)',
      link_project_opsional: 'Project Link (optional)',
      link_github_opsional: 'GitHub Link (optional)',
      link_video_opsional: 'Video Link (YouTube, optional)',
      simpan_project: 'Save Project',
    },
    project_detail: {
      detail_project: 'Project Detail',
      desc_detail: 'View details of projects you have created.',
      nama_project: 'Project Name',
      deskripsi_opsional: 'Description (optional)',
      students_involved: 'Students Involved',
      tambah_pemimpin: 'Team Leader',
      no_leader: 'No leader',
      tambah_rekan: 'Team Members',
      no_member: 'No members',
      time_period: 'Time Period',
      links: 'Links',
      link_video_opsional: 'Video',
      link_github_opsional: 'GitHub',
      link_project_opsional: 'Project',
      learning_corner: 'Learning Corner',
      delete_selected: 'Delete Selected',
      add_new_note: '+ Add New Note',
      no_learning_corner: 'No Learning Corner notes in this project.',
      select_to_delete: 'Select to delete',
      edit: 'Edit',
      delete: 'Delete',
      status_incoming: 'Upcoming',
      status_present: 'Ongoing',
      status_past: 'Finished',
      progress_done: 'Done',
    },
    search: {
      search: 'Search',
      search_placeholder: 'Search projects, certificates, or learning corners...',
      filter_jurusan: 'All Majors',
      filter_keahlian: 'All Skills',
      filter_angkatan: 'All Cohorts',
    },
    result_search: {
      hasil_pencarian: 'Search Results',
      filter_aktif: 'Active filter:',
    },
    sidebar: {
      dashboard: 'Dashboard',
      my_dashboard: 'My Dashboard',
      manajemen_users: 'User Management',
      manajemen_projects: 'Project Management',
      manajemen_sertifikat: 'Certificate Management',
      manajemen_angkatan : 'Angkatan Management',
      dashboard_dosen: 'Lecturer Dashboard',
      mahasiswa_bimbingan: 'Supervised Students',
      projects_bimbingan: 'Supervised Projects',
      sertifikat_bimbingan: 'Supervised Certificates',
      project_mahasiswa: 'Student Projects',
      project_mahasiswa_saya: 'My Projects',
      project_mahasiswa_saya_tambah: 'Add New Project',
      sertifikat_mahasiswa: 'Student Certificates',
      sertifikat_mahasiswa_saya: 'My Certificates',
      sertifikat_mahasiswa_saya_tambah: 'Add New Certificate',
      corner_mahasiswa: 'Student Corner',
      learning_corners: 'Learning Corners',
      setting: 'Setting',
      mode: 'Mode',
      bahasa: 'Language',
      logout: 'Logout',
      login: 'Login',
      login_prompt: 'Are you a student? Login now!',
      register: 'Register',
    },
    footer: {
      footer_rights: '© 2026 Portofolio Mahasiswa. All rights reserved.',
    },
    project_user: {
      project_user_title: 'Project',
      project_user_desc: 'List of projects you participate in as a member.',
      nama_project: 'Project Name',
      tanpa_nama_project:      "Untitled Project",
      tidak_diketahui:         "Unknown",
      selesai:                 "Finished",
      sedang_berjalan:         "Ongoing",
      akan_datang:             "Upcoming",
      sekarang:                "Now",
      diposting: 'Posted',
      no_thumbnail_text: 'No thumbnail available',
      no_thumbnail_description: 'add a video link correctly',
    },
    sertifikat: { 
      sertifikat_title: 'My Certificates',
      sertifikat_desc: 'Manage all the certificates you have here.',
      sertifikat_create_button: 'Add New Certificate',
      sertifikat_no_data: 'No certificates yet.',
      sertifikat_no_data_description: 'Start adding your first certificate!',
      sertifikat_link: 'View Certificate',
      sertifikat_dibuat: 'Added',
      sertifikat_diupdate: 'Updated',
      edit_button: 'Edit',
      delete_button: 'Delete',
    },
    sertifikat_user: { 
      sertifikat_title: 'My Certificates',
      sertifikat_desc: 'Manage all the certificates you have here.',
      sertifikat_create_button: 'Add New Certificate',  
      sertifikat_no_data: 'No certificates yet.',
      sertifikat_no_data_description: 'Start adding your first certificate!',
      sertifikat_link: 'View Certificate',
      sertifikat_dibuat: 'Added',
      sertifikat_diupdate: 'Updated',
    },
    sertifikat_create: { 
      sertifikat_create_title: 'Add New Certificate',
      sertifikat_create_desc: 'Add the certificates you have earned to complete your portfolio.',
      nama_sertifikat: 'Certificate Name',
      error_global_title: 'There are errors with the input:',
      tanggal_terbit: 'Issue Date',
      lembaga_penerbit: 'Issuing Institution',
      upload_file_sertifikat: 'Upload Certificate File',
      upload_file: 'Upload File',
      or_drag_drop: 'or drag and drop',
      max_date: 'Maximum date is today',
      upload_file_desc: 'Allowed formats: JPG, JPEG, PNG, GIF. Maximum size: 5MB',
      upload_file_tips: 'Uploaded files will be stored and accessible via a public link.',
      cancel: 'Cancel',
      save: 'Save Certificate'

    },
    sertifikat_edit: {
      sertifikat_edit_title: 'Edit Certificate',
      sertifikat_edit_desc: 'Update the information of the certificate you have.',
      error_global_title: 'There are errors with the input:',
      nama_sertifikat: 'Certificate Name',
      lembaga_penerbit: 'Issuing Institution',
      tanggal_terbit: 'Issue Date',
      max_date: 'Maximum date is today',
      upload_file_sertifikat: 'Upload Certificate File',
      replace_file: 'Replace File',
      upload_file: 'Upload File',
      or_drag_drop: 'or drag and drop',
      current_file: 'Current File',
      view_current_file: 'View Current File',
      upload_file_desc: 'Allowed formats: JPG, JPEG, PNG, GIF. Maximum size: 5MB',
      upload_file_tips: 'Uploaded files will be stored and accessible via a public link.',
      new_file_preview: 'New File Preview:',
      current_file_preview: 'Current File:',
      additional_info: 'The uploaded file will replace the old file. The old file will be automatically deleted.',
      cancel: 'Cancel',
      update_sertifikat: 'Update Certificate', 
    },
    kelola_user: {
      kelola_user_title: 'Manage Users',
      kelola_user_desc: 'Add, edit, or delete users in the system.',
      status_diterima: 'Accepted',
      status_ditolak: 'Rejected',
      status_sedang_di_ajukan: 'Pending',
      tambah_user: 'Add User',
      edit_user: 'Edit User',
      hapus_user: 'Delete User',
      sertifikat_title: 'Certificates',
      aksi: 'Actions',
    },
    kelola_project: {
      kelola_project_title: 'Manage Projects',
      kelola_project_desc: 'Add, edit, or delete projects in the system.',
      tambah_project: 'Add Project',
      edit_project: 'Edit Project',
      hapus_project: 'Delete Project',
      nama_project: 'Project Name',
      deskripsi: 'Description',
      tanggal_mulai: 'Start Date',
      tanggal_selesai: 'End Date',
      link_project: 'Project Link',
      link_github: 'GitHub Link',
      link_video: 'Video Link',
      diposting: 'Posted',
    },
    kelola_create_project: {
      kelola_create_project_title: 'Add Project',
      kelola_create_project_desc: 'Add projects that students have created.',
      nama_project: 'Project Name',

    },

  }   
};

  const DEFAULT_LANG = 'id';
  let currentLang = localStorage.getItem('lang') || DEFAULT_LANG;

  let translateElements = [];

  function cacheTranslateElements() {
    translateElements = Array.from(document.querySelectorAll('[data-translate]'));
  }

  function applyTranslations() {
    const langData = translations[currentLang] || translations[DEFAULT_LANG];

    translateElements.forEach(el => {
      const page = el.dataset.translatePage || 'sidebar';
      const key  = el.dataset.translate;

      if (!page || !key) return;

      const text = langData?.[page]?.[key] 
                  || translations[DEFAULT_LANG]?.[page]?.[key] 
                  || key;

      if (text !== el.textContent) {
        el.textContent = text;
      }
    });

    const select = document.getElementById('languageSelect');
    if (select) select.value = currentLang;
  }

  window.changeLanguage = function () {
    const select = document.getElementById('languageSelect');
    if (!select) return;

    const newLang = select.value;
    if (newLang === currentLang) return;

    currentLang = newLang;
    localStorage.setItem('lang', newLang);
    document.documentElement.lang = newLang === 'id' ? 'id-ID' : 'en-US';

    applyTranslations();  
  };

  document.addEventListener('DOMContentLoaded', () => {
    const select = document.getElementById('languageSelect');
    if (select) {
      select.value = currentLang;
    }

    cacheTranslateElements();
    applyTranslations();
  });
  window.refreshTranslations = function () {
    cacheTranslateElements(); 
    applyTranslations();
  };